
WITH RELCC AS (

SELECT 

SET2.CODCOLIGADA AS COLIGADA,
SET2.IDHORARIOTURMA AS ID_HORARIO,
SET2.IDTURMADISC AS ID_TURMADISCPLICA,
SET2.RA AS RA_ALUNO,
SET2.DATA as DATA_AULODISCIPLICA,
SET1.DATA_CONVERTIDA AS DATA_ACESSOCATRACA,
SET1.HORAS_CONVERTIDA AS HORA_ACESSOCATRACA,
SET1.NUMEROCARTEIR AS NUMERO_CARTEIRNHA_CATRACA,
SET1.DESCRICAO AS TIPO_ACESSO,
SET1.TIPO_ACESSO AS ENTRADA_SAIDA,
SET2.NOME_DISCIPLICA,
SET2.HORARIO_INICIAL_ALULA,
SET2.HORARIO_FINAL_AULA,

CASE 
	WHEN 100.0 * DATEDIFF(MINUTE, SET3.ENTRADA, SET3.SAIDA) / DATEDIFF(MINUTE, SET2.HORAINICIO, SET2.HORAFIM ) >= 70
        THEN 'Presente'
        ELSE 'Falta'
END

FROM 
(SELECT DISTINCT

E1.ID_PESSOAS,
E1.DATA_CONVERTIDA,
E1.HORAS_CONVERTIDA,
E1.MATRICULA,
E1.NUMEROCARTEIR,
E1.NOME_PESSOA,
E1.equipamento_id,
E1.TIPO_ACESSO,
E1.DESCRICAO,
E1.negado,
E1.DATA_EVA


         FROM ( 
SELECT DISTINCT
PPC.ID AS ID_PESSOAS,
EVA.pessoa_id AS ID_EVENTOSACESSOS,
CONVERT (DATETIME, EVA.DATA, 126)AS DATA_CONVERTIDA,
DBO.CONVERTESEGUNDOSEMHORAS(EVA.HORA) AS HORAS_CONVERTIDA,
EVA.DATA AS DATA_DE_ACESSO,
EVA.hora,
EVA.equipamento_id,
EVA.tipo_acesso,
EVA.descricao,
EVA.negado,
PPC.n_identificador AS MATRICULA,
PPC.NOME AS NOME_PESSOA,
SMA.NUMCARTEIRA AS NUMEROCARTEIR,
SMA.CODTURMA,
EVA.DATA AS DATA_EVA

FROM [192.168.6.12].[SecullumAcessoNet].[DBO].PESSOAS  PPC (NOLOCK ) 

LEFT JOIN [192.168.6.12].[SecullumAcessoNet].[DBO].eventos_acessos EVA (NOLOCK) ON  PPC.id = EVA.pessoa_id 

LEFT JOIN SMATRICPL SMA (NOLOCK) ON  SMA.NUMCARTEIRA COLLATE SQL_Latin1_General_CP1_CI_AI = PPC.n_identificador COLLATE SQL_Latin1_General_CP1_CI_AI

) E1

) AS SET1 INNER JOIN 



(SELECT  
SMA.NUMCARTEIRA AS NUMEROCARTEIRINHA,
SRT.IDTURMADISC AS CODIGO_DISPLICA,
SDI.NOME AS NOME_DISCIPLICA,
SHH.HORAINICIAL AS HORARIO_INICIAL_ALULA,
SHH.HORAFINAL AS HORARIO_FINAL_AULA,
SPP.DATA,
SMA.CODCOLIGADA,
SHO.IDHORARIOTURMA,
SHO.IDTURMADISC,
SMA.RA


 FROM SMATRICPL SMA (NOLOCK) 
 
 INNER JOIN STURMA STU (NOLOCK ) ON SMA.CODCOLIGADA = STU.CODCOLIGADA
                         AND        SMA.CODFILIAL   = STU.CODFILIAL
						 AND        SMA.CODTURMA    = STU.CODTURMA
				         AND        SMA.IDPERLET    = STU.IDPERLET

INNER JOIN STURMADISC SRT (NOLOCK) ON STU.CODCOLIGADA = SRT.CODCOLIGADA
						AND           STU.CODFILIAL   = SRT.CODFILIAL
						AND			  STU.CODTURMA    = SRT.CODTURMA
						AND           STU.IDPERLET    = SRT.IDPERLET

INNER JOIN SDISCIPLINA SDI (NOLOCK) ON SRT.CODCOLIGADA  = SDI.CODCOLIGADA
                      AND              SRT.CODDISC  = SDI.CODDISC

INNER JOIN SHABILITACAOFILIAL SHA (NOLOCK) ON SMA.CODCOLIGADA = SHA.CODCOLIGADA
                       AND                    SMA.IDHABILITACAOFILIAL = SHA.IDHABILITACAOFILIAL

INNER JOIN SHORARIOTURMA SHO (NOLOCK ) ON SRT.CODCOLIGADA = SHO.CODCOLIGADA 
                             AND          SRT.IDTURMADISC = SHO.IDTURMADISC

INNER JOIN SHORARIO SHH ( NOLOCK ) ON SHO.CODCOLIGADA = SHH.CODCOLIGADA
                              AND     SHO.CODHOR      = SHH.CODHOR

INNER JOIN SPLETIVO SPL (NOLOCK) ON SMA.CODCOLIGADA = SPL.CODCOLIGADA 
                              AND   SMA.CODFILIAL   = SPL.CODFILIAL
							  AND   SMA.IDPERLET    = SPL.IDPERLET

LEFT JOIN SPLANOAULA SPP (NOLOCK) ON SHO.CODCOLIGADA = SPP.CODCOLIGADA
                              AND     SHO.IDHORARIOTURMA = SPP.IDHORARIOTURMA
							  AND     SHO.CODHOR         = SPP.CODHOR


							  WHERE SPL.CODPERLET = '2018' 
							  --AND SMA.CODTURMA = 'EM01A101'
							  -- AND SMA.RA = '218001891' 
							  AND SPP.DATA = '2018-04-05' 
							  --AND SPP.IDTURMADISC = '7195'
							  AND SDI.CODCOLIGADA = '1'
							  AND SHA.CODFILIAL = '1'

							  
) SET2 ON SET1.NUMEROCARTEIR = SET2.NUMEROCARTEIRINHA

/*INICIO FUNÇÃO PRESENÇA E FALTA*/

OUTER APPLY
(
    SELECT TOP(1)
        CASE WHEN SET1.ENTRADACATRACA > SET2.HORAINICIO THEN SET1.ENTRADACATRACA ELSE SET2.HORAINICIO END Entrada,
        CASE WHEN SET1.SAIDACATRACA < SET2.HORAFIM THEN SET1.SAIDACATRACA  ELSE SET2.HORAFIM END Saida
    FROM SET1
    WHERE
        SET1.ENTRADACATRACA <= SET2.HORAFIM and
        SET1.SAIDACATRACA >= SET2.HORAINICIO
) SET3

/*FIM FUNÇÃO PRESENÇA E FALTA*/

WHERE 
SET1.DATA_CONVERTIDA = SET2.DATA	AND SET1.NOME_PESSOA = 'AMANDA DE AZEVEDO CORRÊA LIMA' 

GROUP BY 

SET2.CODCOLIGADA,
SET2.RA,
SET1.NUMEROCARTEIR,
SET2.IDHORARIOTURMA,
SET2.IDTURMADISC,
SET2.DATA,
SET1.DATA_CONVERTIDA,
SET1.HORAS_CONVERTIDA,
SET1.DESCRICAO,
SET1.TIPO_ACESSO,
SET2.NOME_DISCIPLICA,
SET1.tipo_acesso,
SET2.HORARIO_INICIAL_ALULA,
SET2.HORARIO_FINAL_AULA

) 

WITH  SOMA  AS (

SELECT	DISTINCT	
RELCC.COLIGADA,
RELCC.RA_ALUNO,
RELCC.NUMERO_CARTEIRNHA_CATRACA,
RELCC.ID_HORARIO,
RELCC.ID_TURMADISCPLICA,
RELCC.NOME_DISCIPLICA,
RELCC.ENTRADA_ACESSO,
RELCC.HORARIO_INICIAL_ALULA,
RELCC.SAINDA_ACESSO,
RELCC.HORARIO_FINAL_AULA,
RELCC.DATA_AULODISCIPLICA,
RELCC.DATA_ACESSOCATRACA,
RELCC.HORA_ACESSOCATRACA,
RELCC.TIPO_ACESSO


FROM	RELCC

WHERE ID_TURMADISCPLICA = '7207'  

GROUP BY 
RELCC.COLIGADA,
RELCC.ID_HORARIO,
RELCC.ID_TURMADISCPLICA,
RELCC.RA_ALUNO,
RELCC.DATA_AULODISCIPLICA,
RELCC.DATA_ACESSOCATRACA,
RELCC.HORA_ACESSOCATRACA,
RELCC.NUMERO_CARTEIRNHA_CATRACA,
RELCC.TIPO_ACESSO,
RELCC.ENTRADA_SAIDA,
RELCC.NOME_DISCIPLICA,
RELCC.ENTRADA_ACESSO,
RELCC.SAINDA_ACESSO,
RELCC.HORARIO_INICIAL_ALULA,
RELCC.HORARIO_FINAL_AULA

),
SOMA_1 AS (

SELECT        SOMA.COLIGADA

FROM	SBOLSALAN		SBL	(NOLOCK)      

  
WHERE	SOMA.CODCOLIGADA	= SBL.CODCOLIGADA


--FROM          SOMA
  
--  WHERE   SOMA.CODCOLIGADA = 1
  
--  GROUP BY 
--            SOMA.COLIGADA,
    
--)

--SELECT    SOMA_1.COLIGADA


		 
--FROM SOMA_1


--GROUP BY 
--SOMA_1.CURSO,


--SELECT * FROM  SHORARIOTURMA SHO

--INNER JOIN SHORARIO SHH ( NOLOCK ) ON SHO.CODCOLIGADA = SHH.CODCOLIGADA
--                              AND     SHO.CODHOR      = SHH.CODHOR 
--WHERE SHO.IDTURMADISC=7207 AND
--EXISTS (SELECT 1 FROM SHORARIOTURMA WHERE HORAINICIAL BETWEEN '07:00' AND '12:00')