SELECT CASE
         WHEN D.PROVDESCBASE = 'P' THEN 'PROVENTO'
         WHEN D.PROVDESCBASE = 'B' THEN 'BASE'
         WHEN D.PROVDESCBASE = 'D' THEN 'DESCONTO'
       END          'PROVENTO',
       A.CHAPA,
       A.NOME,
       A.CODSECAO,
       A.CODFILIAL,
       A.CODSITUACAO,
       SUM(B.VALOR) TOTAL,
	   B.CODEVENTO,
	B.ANOCOMP,
	B.MESCOMP,
	D.DESCRICAO
FROM   PFFINANC B
       INNER JOIN PFUNC A
         ON A.CHAPA = B.CHAPA
       INNER JOIN PPESSOA C
         ON C.CODIGO = A.CODPESSOA
       INNER JOIN PEVENTO D
         ON D.CODIGO = B.CODEVENTO
       INNER JOIN PSECAO E
         ON A.CODSECAO = E.CODIGO
WHERE  B.ANOCOMP = '2018'
       --AND B.CODEVENTO = '0034'
	   AND A.CODSECAO = '01.001.01'
       AND A.CODFILIAL = '1'
GROUP  BY A.CHAPA,
          A.NOME,
          A.CODSECAO,
          A.CODFILIAL,
          A.CODSITUACAO,
          D.PROVDESCBASE,
	B.ANOCOMP,
	B.MESCOMP,
	B.CODEVENTO,
	D.DESCRICAO