SELECT * FROM GLINKSREL WHERE MASTERTABLE='PFFINANC'


SELECT DISTINCT E.CODFILIAL, C.CPF, C.NOME, SUM(B.VALOR) 'BASE' 
FROM PFFINANC B
INNER JOIN PFUNC A ON A.CHAPA = B.CHAPA
INNER JOIN PPESSOA C ON C.CODIGO = A.CODPESSOA
INNER JOIN PEVENTO D ON D.CODIGO = B.CODEVENTO
INNER JOIN PSECAO E ON A.CODSECAO = E.CODIGO
WHERE
B.ANOCOMP=2019 AND
B.MESCOMP=1 AND
D.PROVDESCBASE = 'P' AND
B.NROPERIODO <> 1
and a.CHAPA=37102
GROUP BY C.NOME, C.CPF, E.CODFILIAL
ORDER BY C.NOME

SELECT * FROM PFFINANC WHERE CHAPA=33419 and aNOCOMP=2019 AND MESCOMP=1

SELECT * FROM PFUNC WHERE CHAPA=39972


SELECT * FROM PSECAO
