WITH cte_altera AS(
SELECT --'UPDATE PEVENTO SET NATRUBRICA = '+A.NATRUBRICA+ ' WHERE CODIGO= '+B.CODIGO+' AND CODCOLIGADA= '+CONVERT( VARCHAR, B.CODCOLIGADA)
A.CODIGO 'COD_COLIGADA3', B.CODIGO 'COD_COLIGADA2', 
A.NATRUBRICA 'RUB_COL3',B.NATRUBRICA 'NATRUB_COL2',--, B.NATRUBRICA 'NATRUB_COL3', 
A.DESCRICAO 'DESC_COL3', B.DESCRICAO 'DESC_COL2'--, A.INATIVO
FROM
(SELECT DISTINCT
	CODIGO,CODRUBRICA,NATRUBRICA,DESCRICAO, INATIVO
FROM 
	PEVENTO 
WHERE 
	INATIVO = 0 AND
	CODRUBRICA IS NOT NULL AND
	CODCOLIGADA=3) 
	
A INNER JOIN

(SELECT 
	CODIGO,CODRUBRICA,NATRUBRICA,DESCRICAO, INATIVO,CODCOLIGADA
FROM 
	PEVENTO 
WHERE 	
	--INATIVO IS NULL AND
	CODCOLIGADA=6)

B ON --B.CODIGO = A.CODIGO AND 
--B.DESCRICAO LIKE A.DESCRICAO+'%'
B.DESCRICAO = A.DESCRICAO
--B.CODIGO = A.CODIGO
--WHERE
--B.NATRUBRICA  IS NULL
) 
--update t
--set t.natrubrica = cte_altera.RUB_COL3
--from PEVENTO t
--inner join cte_altera on
--	t.codigo = cte_altera.COD_COLIGADA2
--where 
--t.CODCOLIGADA= 6 --and t.NATRUBRICA = cte_altera.NATRUB_COL2











/*
SELECT CODRUBRICA, NATRUBRICA, 3 'CODCOLIGADA', CODIGO, TOTALIZADOR, CHAVE, COMPOECOMISSAO, PROVDESCBASE, VALHORDIAREF, PORCINCID, CODIGOCALCULO, PRIORIDADE, FORMULAVALOR, FORMULAHORA, FORMULAREF, FORMULACRITICA, INCINSS, INCIRRF, INCFGTS, INCRAIS, INCINFREND, INCDSR, INCVALETRANSP, INCIRRFFERIAS, INCTERCOFERIAS, INCSALFAMILIA, INCINSS13, INCIRRF13, INCACUMULADOR, INCSALARIO, PROPORCADMISSAO, PROPORCLICENCA, PROPORCFERIAS, DEDUTIVELIRRF, ESTCALCULO, ESTCALCFERIAS, ESTCALCSALFAM, ESTCALCVALETR, ESTINSS13, GRUPOAAS, EVTALANCAR, CONTACREDITO, CONTADEBITO, NROHISTPADRAO, COMPLHISTORICO, APLICACAO, CGCREDITO, CGDEBITO, CODEVENTODIF, CODRATEIO, DESCRICAO, BASESALCOMPOSTO, DESCONTOPERDOADO, PROPPORTOMADOR, PAGOBRIGATORIO, TEMINTCONTCC, TEMINTCONTCD, TEMINTCONTGC, TEMINTCONTGD, TEMINTFUNCCC, TEMINTFUNCCD, TEMINTFUNCGC, TEMINTFUNCGD, CONTPARCIAL, INCSUBSTITUICAO, ESTIRRFFERIAS, ESTFGTS13, ESTIRRF13, CODEVENTOINSUF, CCUSTO, INCPENSAO, INCPENSAOFERIAS, INCPENSAO13SAL, INCPENSAOPARTICIP, IDANOTACAO, FORMCOMPLHIST, PERCALCRATEIO, ESTINSS, ESTIRRF, ESTFGTS, INCFGTS13, PROPORCDEMISSAO, SEGUERATEIOSALCMP, CONTAREVERSAO, FORMULAEVTRELAC, NATREM, QUADROREM, EVENTOEXIBIDOENTRADADADOSWEB, ORDEMCALCULO, DEDUTIVELIRRF13, DEDUTIVELIRRFFERIAS, CODRUBRICA, ID, SEGUERATEIOMOVENSINO, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON, NATRUBRICA, INCINSSSUSPENSA, INCIRRFSUSPENSA, INCFGTSSUSPENSA, INATIVO, NRPROCESSOINSS, TPPROCESSOINSS, EXTDECISAOINSS, NRPROCESSOIRRF, TPPROCESSOIRRF, NRPROCESSOFGTS, TPPROCESSOFGTS, INCSINDSUSPENSA, NRPROCESSOSIND, TPPROCESSOSIND, INCSALMATERNSUSPENSA, NRPROCESSOSALMATERN, TPPROCESSOSALMATERN, INCIDECUSTOFUNCIONARIO, CODTPBENEFICIO, CODTPDESCONTO, IDITEMCONTABIL, IDCLASSEVALOR, INCPIS, ESTPIS, COMPOEREMBASE, SEGUERATEIOMOVTEMPCONTAB, SEGUERATEIOMOVENSINOCONTAB, INCINSSEXCLUSIVASEGURADO, RENDNAOTRIBACORDOINTERNAC, NAOEBASECALCACORDOINTERNAC, INCINSS13SUSPENSA, INCIRRF13SUSPENSA, INCFGTS13SUSPENSA
FROM dbo.PEVENTO 
WHERE
CODCOLIGADA=2


BEGIN TRANSACTION
UPDATE dbo.PEVENTO
SET CODRUBRICA = '300'
	, NATRUBRICA = '9210'
WHERE CODCOLIGADA = 3 AND CODIGO = '0005'
GO

--COMMIT*/



