SELECT DISTINCT D.NOMEFANTASIA FILIAL, C.CODIGO CODSECAO, C.DESCRICAO SECAO, A.CHAPA, A.CHAPA, B.NOME, 
CONVERT(VARCHAR(10),DATAADMISSAO,103) ADMISSAO, 
CONVERT(VARCHAR(10),DTFIMPERAQUIS,103) FIM,
DTFIMPERAQUIS,
CONVERT(VARCHAR(10),DATEADD(MONTH,11,DTFIMPERAQUIS)-1,103) LIMITE,
      CASE WHEN DTFIMPERAQUIS < GETDATE()
           THEN DATEDIFF(MONTH,DTINIPERAQUIS,DTFIMPERAQUIS) + CASE WHEN DTFIMPERAQUIS - (DATEADD(MONTH,DATEDIFF(MONTH,DTINIPERAQUIS,DTFIMPERAQUIS),DTINIPERAQUIS)-1)>=15 THEN 1 ELSE 0 END
      ELSE 0
      END AVOS_V,
      CASE WHEN DTFIMPERAQUIS < GETDATE()
           THEN CASE WHEN (SELECT ISNULL(SUM(REF/8),0) FALTAS
                FROM PFFINANC
                WHERE CODCOLIGADA=B.CODCOLIGADA AND
                      CHAPA=B.CHAPA AND
                      DTPAGTO BETWEEN A.DTINIPERAQUIS
                      AND A.DTFIMPERAQUIS
                      AND CODEVENTO IN (SELECT CODIGO FROM PEVENTO WHERE CODIGOCALCULO=8)) >=33
     THEN 0
     ELSE CASE WHEN (SELECT ISNULL(SUM(REF/8),0) FALTAS
          FROM PFFINANC
          WHERE CODCOLIGADA=B.CODCOLIGADA AND
                CHAPA=B.CHAPA AND
                DTPAGTO BETWEEN A.DTINIPERAQUIS AND A.DTFIMPERAQUIS AND
                CODEVENTO IN (SELECT CODIGO FROM PEVENTO WHERE CODIGOCALCULO=8)) >=24
          THEN 12-ISNULL((SELECT SUM(ISNULL(DATEDIFF(DAY, DTINIGOZO, DTFIMGOZO+1),0))
          FROM PFHSTFER
          WHERE CODCOLIGADA=B.CODCOLIGADA AND
                CHAPA=B.CHAPA AND
                DTFIMPERAQUIS=A.DTFIMPERAQUIS AND
                DTINIPERAQUIS=A.DTINIPERAQUIS AND
                DTINIGOZO IS NOT NULL),0)
         ELSE CASE WHEN (SELECT ISNULL(SUM(REF/8),0) FALTAS
                         FROM PFFINANC
                         WHERE CODCOLIGADA=B.CODCOLIGADA AND
                               CHAPA=B.CHAPA AND DTPAGTO BETWEEN A.DTINIPERAQUIS AND A.DTFIMPERAQUIS AND
                               CODEVENTO IN (SELECT CODIGO FROM PEVENTO WHERE CODIGOCALCULO=8)) >=15
         THEN 18-ISNULL((SELECT SUM(ISNULL(DATEDIFF(DAY, DTINIGOZO, DTFIMGOZO+1),0))
                         FROM PFHSTFER
                         WHERE CODCOLIGADA=B.CODCOLIGADA AND
                               CHAPA=B.CHAPA AND
                               DTFIMPERAQUIS=A.DTFIMPERAQUIS AND
                               DTINIPERAQUIS=A.DTINIPERAQUIS AND DTINIGOZO IS NOT NULL),0)
                ELSE CASE WHEN (SELECT ISNULL(SUM(REF/8),0) FALTAS
                                FROM PFFINANC
                                WHERE CODCOLIGADA=B.CODCOLIGADA AND
                                      CHAPA=B.CHAPA AND
                                      DTPAGTO BETWEEN A.DTINIPERAQUIS AND A.DTFIMPERAQUIS AND
                                      CODEVENTO IN (SELECT CODIGO FROM PEVENTO WHERE CODIGOCALCULO=8)) >=6
                      THEN 24-ISNULL((SELECT SUM(ISNULL(DATEDIFF(DAY, DTINIGOZO, DTFIMGOZO+1),0)) FROM PFHSTFER WHERE CODCOLIGADA=B.CODCOLIGADA AND CHAPA=B.CHAPA AND DTFIMPERAQUIS=A.DTFIMPERAQUIS AND DTINIPERAQUIS=A.DTINIPERAQUIS AND DTINIGOZO IS NOT NULL),0)
                      ELSE 30-ISNULL((SELECT SUM(ISNULL(DATEDIFF(DAY, DTINIGOZO, DTFIMGOZO+1),0)) FROM PFHSTFER WHERE CODCOLIGADA=B.CODCOLIGADA AND CHAPA=B.CHAPA AND DTFIMPERAQUIS=A.DTFIMPERAQUIS AND DTINIPERAQUIS=A.DTINIPERAQUIS AND DTINIGOZO IS NOT NULL),0)
                      END
                END
           END
     END
     ELSE 0
END DIAS_V,
CASE WHEN DTFIMPERAQUIS>=GETDATE()
     THEN 0
     ELSE (SELECT ISNULL(SUM(REF/8),0) FALTAS FROM PFFINANC WHERE CODCOLIGADA=B.CODCOLIGADA AND CHAPA=B.CHAPA AND DTPAGTO BETWEEN A.DTINIPERAQUIS AND A.DTFIMPERAQUIS AND CODEVENTO IN (SELECT CODIGO FROM PEVENTO WHERE CODIGOCALCULO=8))
END FALTAS_V,
CASE WHEN DTFIMPERAQUIS<GETDATE()
     THEN DATEDIFF(MONTH,DTFIMPERAQUIS,GETDATE())+CASE WHEN GETDATE()-(DATEADD(MONTH,DATEDIFF(MONTH,DTINIPERAQUIS,GETDATE()),DTINIPERAQUIS)-1)>=15 THEN 1 ELSE 0 END
     ELSE DATEDIFF(MONTH,DTINIPERAQUIS,GETDATE())+CASE WHEN GETDATE()-(DATEADD(MONTH,DATEDIFF(MONTH,DTINIPERAQUIS,GETDATE()),DTINIPERAQUIS)-1)>=15 THEN 1 ELSE 0 END
END AVOS_P,
CASE WHEN DTFIMPERAQUIS>=GETDATE()
     THEN CASE WHEN (SELECT ISNULL(SUM(REF/8),0) FALTAS FROM PFFINANC WHERE CODCOLIGADA=B.CODCOLIGADA AND CHAPA=B.CHAPA AND DTPAGTO BETWEEN A.DTINIPERAQUIS AND A.DTFIMPERAQUIS AND CODEVENTO IN (SELECT CODIGO FROM PEVENTO WHERE CODIGOCALCULO=8)) >= 33
               THEN 0
               ELSE CASE WHEN (SELECT ISNULL(SUM(REF/8),0) FALTAS FROM PFFINANC WHERE CODCOLIGADA=B.CODCOLIGADA AND CHAPA=B.CHAPA AND DTPAGTO BETWEEN A.DTINIPERAQUIS AND A.DTFIMPERAQUIS AND CODEVENTO IN (SELECT CODIGO FROM PEVENTO WHERE CODIGOCALCULO=8)) >= 24
                         THEN (12/12*(DATEDIFF(MONTH,GETDATE(),DTINIPERAQUIS)+CASE WHEN GETDATE()-(DATEADD(MONTH,DATEDIFF(MONTH,GETDATE(),DTINIPERAQUIS),DTINIPERAQUIS)-1)>=15 THEN 1 ELSE 0 END))-ISNULL((SELECT SUM(ISNULL(DATEDIFF(DAY, DTINIGOZO, DTFIMGOZO+1),0)) FROM PFHSTFER WHERE CODCOLIGADA=B.CODCOLIGADA AND CHAPA=B.CHAPA AND DTFIMPERAQUIS=A.DTFIMPERAQUIS AND DTINIPERAQUIS=A.DTINIPERAQUIS AND DTINIGOZO IS NOT NULL),0)
                         ELSE CASE WHEN (SELECT ISNULL(SUM(REF/8),0) FALTAS FROM PFFINANC WHERE CODCOLIGADA=B.CODCOLIGADA AND CHAPA=B.CHAPA AND DTPAGTO BETWEEN A.DTINIPERAQUIS AND A.DTFIMPERAQUIS AND CODEVENTO IN (SELECT CODIGO FROM PEVENTO WHERE CODIGOCALCULO=8)) >= 15
                                   THEN (18/12*(DATEDIFF(MONTH,GETDATE(),DTINIPERAQUIS)+CASE WHEN GETDATE()-(DATEADD(MONTH,DATEDIFF(MONTH,GETDATE(),DTINIPERAQUIS),DTINIPERAQUIS)-1)>=15 THEN 1 ELSE 0 END))-ISNULL((SELECT SUM(ISNULL(DATEDIFF(DAY, DTINIGOZO, DTFIMGOZO+1),0)) FROM PFHSTFER WHERE CODCOLIGADA=B.CODCOLIGADA AND CHAPA=B.CHAPA AND DTFIMPERAQUIS=A.DTFIMPERAQUIS AND DTINIPERAQUIS=A.DTINIPERAQUIS AND DTINIGOZO IS NOT NULL),0)
                                   ELSE CASE WHEN (SELECT ISNULL(SUM(REF/8),0) FALTAS FROM PFFINANC WHERE CODCOLIGADA=B.CODCOLIGADA AND CHAPA=B.CHAPA AND DTPAGTO BETWEEN A.DTINIPERAQUIS AND A.DTFIMPERAQUIS AND CODEVENTO IN (SELECT CODIGO FROM PEVENTO WHERE CODIGOCALCULO=8)) >= 6
                                             THEN (24/12*(DATEDIFF(MONTH,DTINIPERAQUIS,GETDATE())+CASE WHEN GETDATE()-(DATEADD(MONTH,DATEDIFF(MONTH,DTINIPERAQUIS,GETDATE()),DTINIPERAQUIS)-1)>=15 THEN 1 ELSE 0 END))-ISNULL((SELECT SUM(ISNULL(DATEDIFF(DAY, DTINIGOZO, DTFIMGOZO+1),0)) FROM PFHSTFER WHERE CODCOLIGADA=B.CODCOLIGADA AND CHAPA=B.CHAPA AND DTFIMPERAQUIS=A.DTFIMPERAQUIS AND DTINIPERAQUIS=A.DTINIPERAQUIS AND DTINIGOZO IS NOT NULL),0)
                                             ELSE (30/12*(DATEDIFF(MONTH,DTINIPERAQUIS,GETDATE())+CASE WHEN GETDATE()-(DATEADD(MONTH,DATEDIFF(MONTH,DTINIPERAQUIS,GETDATE()),DTINIPERAQUIS)-1)>=15 THEN 1 ELSE 0 END))-ISNULL((SELECT SUM(ISNULL(DATEDIFF(DAY, DTINIGOZO, DTFIMGOZO+1),0)) FROM PFHSTFER WHERE CODCOLIGADA=B.CODCOLIGADA AND CHAPA=B.CHAPA AND DTFIMPERAQUIS=A.DTFIMPERAQUIS AND DTINIPERAQUIS=A.DTINIPERAQUIS AND DTINIGOZO IS NOT NULL),0)
                                        END
                              END
                   END
          END
     ELSE CASE WHEN (SELECT ISNULL(SUM(REF/8),0) FALTAS FROM PFFINANC WHERE CODCOLIGADA=B.CODCOLIGADA AND CHAPA=B.CHAPA AND DTPAGTO BETWEEN A.DTFIMPERAQUIS AND GETDATE() AND CODEVENTO IN (SELECT CODIGO FROM PEVENTO WHERE CODIGOCALCULO=8)) >= 33
               THEN 0
               ELSE CASE WHEN (SELECT ISNULL(SUM(REF/8),0) FALTAS FROM PFFINANC WHERE CODCOLIGADA=B.CODCOLIGADA AND CHAPA=B.CHAPA AND DTPAGTO BETWEEN A.DTFIMPERAQUIS AND GETDATE() AND CODEVENTO IN (SELECT CODIGO FROM PEVENTO WHERE CODIGOCALCULO=8)) >= 24
                         THEN (12/12*(DATEDIFF(MONTH,DTFIMPERAQUIS,GETDATE())+CASE WHEN GETDATE()-(DATEADD(MONTH,DATEDIFF(MONTH,GETDATE(),DTINIPERAQUIS),DTINIPERAQUIS)-1)>=15 THEN 1 ELSE 0 END))
                         ELSE CASE WHEN (SELECT ISNULL(SUM(REF/8),0) FALTAS FROM PFFINANC WHERE CODCOLIGADA=B.CODCOLIGADA AND CHAPA=B.CHAPA AND DTPAGTO BETWEEN A.DTFIMPERAQUIS AND GETDATE() AND CODEVENTO IN (SELECT CODIGO FROM PEVENTO WHERE CODIGOCALCULO=8)) >= 15
                                   THEN (18/12*(DATEDIFF(MONTH,DTFIMPERAQUIS,GETDATE())+CASE WHEN GETDATE()-(DATEADD(MONTH,DATEDIFF(MONTH,GETDATE(),DTINIPERAQUIS),DTINIPERAQUIS)-1)>=15 THEN 1 ELSE 0 END))
                                   ELSE CASE WHEN (SELECT ISNULL(SUM(REF/8),0) FALTAS FROM PFFINANC WHERE CODCOLIGADA=B.CODCOLIGADA AND CHAPA=B.CHAPA AND DTPAGTO BETWEEN A.DTFIMPERAQUIS AND GETDATE() AND CODEVENTO IN (SELECT CODIGO FROM PEVENTO WHERE CODIGOCALCULO=8)) >= 6
                                             THEN (24/12*(DATEDIFF(MONTH,DTFIMPERAQUIS,GETDATE())+CASE WHEN GETDATE()-(DATEADD(MONTH,DATEDIFF(MONTH,DTINIPERAQUIS,GETDATE()),DTINIPERAQUIS)-1)>=15 THEN 1 ELSE 0 END))
                                             ELSE (30/12*(DATEDIFF(MONTH,DTFIMPERAQUIS,GETDATE())+CASE WHEN GETDATE()-(DATEADD(MONTH,DATEDIFF(MONTH,DTINIPERAQUIS,GETDATE()),DTINIPERAQUIS)-1)>=15 THEN 1 ELSE 0 END))
                                        END
                              END
                   END
          END
END DIAS_P,
CASE WHEN DTFIMPERAQUIS>=GETDATE()
     THEN (SELECT ISNULL(SUM(REF/8),0) FALTAS FROM PFFINANC WHERE CODCOLIGADA=B.CODCOLIGADA AND CHAPA=B.CHAPA AND DTPAGTO BETWEEN A.DTINIPERAQUIS AND A.DTFIMPERAQUIS AND CODEVENTO IN (SELECT CODIGO FROM PEVENTO WHERE CODIGOCALCULO=8))
     ELSE (SELECT ISNULL(SUM(REF/8),0) FALTAS FROM PFFINANC WHERE CODCOLIGADA=B.CODCOLIGADA AND CHAPA=B.CHAPA AND DTPAGTO BETWEEN A.DTFIMPERAQUIS AND GETDATE() AND CODEVENTO IN (SELECT CODIGO FROM PEVENTO WHERE CODIGOCALCULO=8))
END FALTA_P,
30 - ISNULL((SELECT ISNULL(SUM(NRODIASCORRIDOS),0) FROM PFHSTFER WHERE CODCOLIGADA=B.CODCOLIGADA AND CHAPA=B.CHAPA AND DTFIMPERAQUIS=A.DTFIMPERAQUIS AND DTINIPERAQUIS=A.DTINIPERAQUIS AND DTINIGOZO IS NOT NULL),0) DIAS_GOZO,
CONVERT(VARCHAR(10),B.INICPROGFERIAS1,103) PROG, NULL PREV, 1 AS QTD,
E.NOME FUNCAO
FROM PFHSTFER A (NOLOCK)
JOIN PFUNC  B (NOLOCK) ON (A.CODCOLIGADA=B.CODCOLIGADA AND A.CHAPA=B.CHAPA)
JOIN PSECAO C (NOLOCK) ON (C.CODCOLIGADA=B.CODCOLIGADA AND C.CODIGO=B.CODSECAO)
JOIN GFILIAL D (NOLOCK) ON (B.CODCOLIGADA=D.CODCOLIGADA AND B.CODFILIAL=D.CODFILIAL)
JOIN PFUNCAO E (NOLOCK) ON (E.CODCOLIGADA=B.CODCOLIGADA AND E.CODIGO=B.CODFUNCAO)
WHERE A.CODCOLIGADA= 2
  AND A.DTINIGOZO IS NULL
  AND B.CODSITUACAO IN ('A','F')
  AND B.CODTIPO IN ('N','Z')
  AND B.NOME = 'CARLA DOS ANJOS SILVA DORNELAS'
  
 ORDER BY 6