SELECT 
1 'CODCOLIGADA', 
FCFO.CODCFO 'CODCFO', 1 'IDPGTO', 'BOLETO' 'DESCRICAO', CONVERT(VARCHAR,'I') 'FORMAPAGAMENTO', 
FCFO.NOMEFANTASIA 'FAVORECIDO', FCFO.CGCCFO 'CGCFAVORECIDO',1 'ATIVO', 1 'CODCOLCFO', 'mestre' 'RECCREATEDBY' 
FROM FCFO 
--LEFT JOIN FDADOSPGTO ON FDADOSPGTO.CODCFO = FCFO.CODCFO AND FDADOSPGTO.CODCOLIGADA = FCFO.CODCOLIGADA
WHERE
 --FDADOSPGTO.DESCRICAO IS NULL AND
 FCFO.PESSOAFISOUJUR = 'J' AND
 FCFO.CODCOLIGADA=1 AND
 NOT EXISTS (SELECT * FROM FDADOSPGTO WHERE 
 				FCFO.CODCFO = FDADOSPGTO.CODCFO AND FCFO.CODCOLIGADA = FDADOSPGTO.CODCOLIGADA
 				AND FDADOSPGTO.FORMAPAGAMENTO <> 1)