INSERT INTO dbo.SNOTAETAPA (CODCOLIGADA, CODETAPA, TIPOETAPA, IDTURMADISC, RA, NOTAFALTA, RECCREATEDBY, RECCREATEDON)
SELECT DISTINCT 
	1 'CODCOLIGADA',
	B.CODETAPA,
	B.TIPOETAPA,
	B.IDTURMADISC,
	A.RA, 
	A.SOMANOTA/10 'SOMANOTA',  
	GETDATE() RECCREATEDBY,
	GETDATE() RECCREATEDON
	
FROM
(SELECT DISTINCT 
		SMATRICULA.RA,		
	SPLETIVO.CODPERLET,
       STURMADISC.CODTURMA,
       STURMADISC.CODDISC,
       SMATRICULA.CODCOLIGADA,
       SMATRICULA.IDTURMADISC,
       SUM(SNOTAETAPA.NOTAFALTA) 'SOMANOTA',
       PPESSOA.NOME
FROM   SMATRICULA (NOLOCK)
       JOIN STURMADISC (NOLOCK)
         ON ( SMATRICULA.CODCOLIGADA = STURMADISC.CODCOLIGADA
              AND SMATRICULA.IDTURMADISC = STURMADISC.IDTURMADISC )
       JOIN SPLETIVO (NOLOCK)
         ON ( SPLETIVO.CODCOLIGADA = STURMADISC.CODCOLIGADA
              AND SPLETIVO.IDPERLET = STURMADISC.IDPERLET )
       JOIN SALUNO (NOLOCK)
         ON ( SMATRICULA.CODCOLIGADA = SALUNO.CODCOLIGADA
              AND SMATRICULA.RA = SALUNO.RA )
       JOIN PPESSOA (NOLOCK)
         ON ( SALUNO.CODPESSOA = PPESSOA.CODIGO )
       JOIN SNOTAETAPA (NOLOCK) ON SNOTAETAPA.CODCOLIGADA = SMATRICULA.CODCOLIGADA AND SNOTAETAPA.IDTURMADISC = SMATRICULA.IDTURMADISC AND SNOTAETAPA.RA = SMATRICULA.RA
WHERE  SMATRICULA.CODCOLIGADA = 1
       AND SPLETIVO.CODPERLET = '2-2017'
       AND STURMADISC.IDTURMADISC = '14458'
       --AND STURMADISC.CODDISC = '0413/1'
	   AND SNOTAETAPA.TIPOETAPA = 'N'
	   --AND SNOTAETAPA.CODETAPA<>0
	   AND SNOTAETAPA.CODETAPA = 6
       AND SMATRICULA.CODSTATUS IN (SELECT CODSTATUS
                                    FROM   SSTATUS
                                    WHERE  CODCOLIGADA = SMATRICULA.CODCOLIGADA
                                           AND DISCIPLINA = 'S'
                                           AND DIBLOQNOTAFALTA = 'N'
                                           AND PLDIARIO = 'S') 
										   GROUP BY SMATRICULA.RA,		
	SPLETIVO.CODPERLET,
       STURMADISC.CODTURMA,
       STURMADISC.CODDISC,
       SMATRICULA.CODCOLIGADA,
       SMATRICULA.IDTURMADISC,
       PPESSOA.NOME) A
INNER JOIN
--INSERT INTO dbo.SNOTAETAPA (CODCOLIGADA, CODETAPA, TIPOETAPA, IDTURMADISC, RA, IDGRUPO, CODCONCEITO, NOTAFALTA, AULASDADAS, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON, CONCEITOECTS)
(SELECT DISTINCT 
		SMATRICULA.RA,		
	SPLETIVO.CODPERLET,
       STURMADISC.CODTURMA,
       STURMADISC.CODDISC,
       SMATRICULA.CODCOLIGADA,
       SMATRICULA.IDTURMADISC,
	   SETAPAS.CODETAPA,
	   SETAPAS.TIPOETAPA
FROM   SMATRICULA (NOLOCK)
       JOIN STURMADISC (NOLOCK)
         ON SMATRICULA.CODCOLIGADA = STURMADISC.CODCOLIGADA
              AND SMATRICULA.IDTURMADISC = STURMADISC.IDTURMADISC
       JOIN SPLETIVO (NOLOCK)
         ON SPLETIVO.CODCOLIGADA = STURMADISC.CODCOLIGADA
              AND SPLETIVO.IDPERLET = STURMADISC.IDPERLET
	   JOIN SETAPAS
		ON SETAPAS.CODCOLIGADA = STURMADISC.CODCOLIGADA
			AND SETAPAS.IDTURMADISC = STURMADISC.IDTURMADISC
WHERE
	  SPLETIVO.CODPERLET = '2-2017'
       AND STURMADISC.IDTURMADISC <> '14458'
	   AND SETAPAS.TIPOETAPA='N'
	   AND SETAPAS.CODETAPA='7'	) 
	B ON B.RA = A.RA AND A.CODPERLET = B.CODPERLET AND A.SOMANOTA IS NOT NULL

 WHERE 	
not exists (SELECT * 
                        from SNOTAETAPA as S1
                        where S1.CODCOLIGADA = A.CODCOLIGADA
                              and S1.RA = A.RA
							  and S1.CODETAPA='7'
							  and S1.TIPOETAPA='N')
							 

							 --delete from SNOTAETAPA where CODETAPA=7 and TIPOETAPA='n'
