UPDATE dbo.SDISCGRADE
SET VALORCREDITO = '72'
WHERE CODCOLIGADA = 1 
AND CODGRADE='AGRO8' 

UPDATE dbo.SDISCGRADE
SET VALORCREDITO = '65.4546'
WHERE CODCOLIGADA = 1 
AND CODGRADE='AGRO10'

UPDATE dbo.SDISCGRADE
SET VALORCREDITO = '65.4546'
WHERE CODCOLIGADA = 1 
AND CODGRADE='AGRO11'

UPDATE dbo.SDISCGRADE
SET VALORCREDITO = '72'
WHERE CODCOLIGADA = 1 
AND CODGRADE='ZOO9' 

UPDATE dbo.SDISCGRADE
SET VALORCREDITO = '65.4546'
WHERE CODCOLIGADA = 1 
AND CODGRADE='ZOO11'

UPDATE dbo.SDISCGRADE
SET VALORCREDITO = '65.4546'
WHERE CODCOLIGADA = 1 
AND CODGRADE='ZOO12'

UPDATE dbo.SDISCGRADE
SET VALORCREDITO = '22.40'
WHERE CODCOLIGADA = 1 
AND CODGRADE='CSTA06'

UPDATE dbo.SDISCGRADE
SET VALORCREDITO = '19.0750'
WHERE CODCOLIGADA = 1 
AND CODGRADE='CSTA04'

UPDATE dbo.SDISCGRADE
SET VALORCREDITO = '30.9889'
WHERE CODCOLIGADA = 1 
AND CODGRADE='SIN06'





--SELECT * FROM GLINKSREL WHERE MASTERTABLE='SGRADE' AND CHILDTABLE='B'
--'CODCOLIGADA,CODCURSO,CODHABILITACAO,CODGRADE'

--SELECT * FROM GLINKSREL WHERE MASTERTABLE='B' AND CHILDTABLE='C'
--'CODCOLIGADA,CODCURSO,CODHABILITACAO,CODGRADE,CODPERIODO'