
select * from TTBORCAMENTOCONT WHERE CODTBORCAMENTO='2.3.9.01'

SELECT 1 'CODCOLIGADA', IDTBORCAMENTOCONT, CODCOLTBORCAMENTO, CODTBORCAMENTO, 1 'CODCOLCONTA', CODCONTA, 
DEBOUCRED, 100 'PERCENTUAL', 
'mestre' 'RECCREATEDBY', '2018-06-16' 'RECCREATEDON', 'mestre' RECMODIFIEDBY, '2018-06-16' RECMODIFIEDON
FROM dbo.TTBORCAMENTOCONT
WHERE CODCOLIGADA = 1 AND CODCOLTBORCAMENTO = 1 AND CODTBORCAMENTO = '1.1.1.03'

2.3.9.01
CONVERT ( DATETIME, CONVERT ( VARCHAR, GETDATE(), 120) )
--------------------------------------------------------------

SELECT * FROM GAUTOINC WHERE CODAUTOINC='idtborcamentocont'

639
UPDATE dbo.GAUTOINC
SET VALAUTOINC = (select max(IDTBORCAMENTOCONT) from TTBORCAMENTOCONT WHERE CODCOLIGADA=1)
WHERE CODCOLIGADA = 1 AND CODSISTEMA = 'T' AND CODAUTOINC = 'IDTBORCAMENTOCONT'
GO


INSERT INTO dbo.TTBORCAMENTOCONT (CODCOLIGADA, IDTBORCAMENTOCONT, CODCOLTBORCAMENTO, CODTBORCAMENTO, CODCOLCONTA, CODCONTA, DEBOUCRED, PERCENTUAL, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
VALUES (1, 640, 1, '1.1.1.03', 1, '2.1.2.06.01.0031', 1, 100, 'mestre', '2018-06-16', 'mestre', '2018-06-16')
GO

--=========================================================--

UPDATE dbo.GAUTOINC
SET VALAUTOINC = (select max(IDTBORCAMENTOCONT) from TTBORCAMENTOCONT WHERE CODCOLIGADA=2)
WHERE CODCOLIGADA = 2 AND CODSISTEMA = 'T' AND CODAUTOINC = 'IDTBORCAMENTOCONT'
GO
----------------------------------------------------

SELECT 2 'CODCOLIGADA', A.IDTBORCAMENTOCONT,
/*(SELECT 
		MAX(IDTBORCAMENTOCONT) 
			FROM TTBORCAMENTOCONT 
			WHERE CODCOLIGADA=1)+
			ROW_NUMBER() OVER(PARTITION BY A.CODCOLTBORCAMENTO ORDER BY A.CODCOLCONTA ASC) 'IDTBORCAMENTOCONT', */
A.CODCOLTBORCAMENTO, A.CODTBORCAMENTO, A.CODCOLCONTA, 
A.CODCONTA, 2 'DEBOUCRED', A.PERCENTUAL, A.RECCREATEDBY, A.RECCREATEDON, A.RECMODIFIEDBY, A.RECMODIFIEDON
FROM TTBORCAMENTO B
INNER JOIN TTBORCAMENTOCONT A ON A.CODCOLTBORCAMENTO = B.CODCOLIGADA AND A.CODTBORCAMENTO = B.CODTBORCAMENTO
WHERE
A.CODCOLIGADA=1

-===============CONSULTA DO PLANO DE CONTAS===================--

SELECT * FROM TMOV A
INNER JOIN FLAN B ON B.CODCOLIGADA = A.CODCOLIGADA AND B.IDMOV = A.IDMOV
--INNER JOIN CPARTIDA C ON C.CODCOLIGADA = B.CODCOLIGADA AND C.IDLANCAMENTO = B.IDLAN
INNER JOIN FLANRATCCU D ON A.CODCOLIGADA = B.CODCOLIGADA AND A.IDMOV = B.IDMOV
--INNER JOIN TTBORCAMENTO D ON D.CODBORCAMENTO =  
WHERE
YEAR(B.DATAEMISSAO)='2018'


SELECT * FROM CPARTIDA WHERE DATA='2018-06-16'

SELECT * FROM FLANRATCCU WHERE IDLAN=678966







