select TOP 1
	/*FDADOSPGTO.DESCRICAO+' - '+FDADOSPGTO.NOMEAGENCIA+' - AG.: '+convert(VARCHAR,FDADOSPGTO.CODIGOAGENCIA)+'-'+FDADOSPGTO.DIGITOAGENCIA+' - CONTA: '+FDADOSPGTO.CONTACORRENTE+'-'+FDADOSPGTO.DIGITOCONTA+'. FAVORECIDO: '+FDADOSPGTO.FAVORECIDO*/
	 CASE WHEN DESCRICAO LIKE 'BOLETO%' THEN 'FORMA DE PGTO: BOLETO'+' - FAVORECIDO: '+ISNULL(FDADOSPGTO.FAVORECIDO, '')
	 ELSE 
		 ISNULL(FDADOSPGTO.DESCRICAO, '')+' - '+
		 ISNULL(FDADOSPGTO.NOMEAGENCIA, '')+' - AG.: '+
		 ISNULL(convert(VARCHAR, FDADOSPGTO.CODIGOAGENCIA), '')+' - '+
		 ISNULL(FDADOSPGTO.DIGITOAGENCIA, '')+' - CONTA: '+
		 ISNULL(FDADOSPGTO.CONTACORRENTE, '')+'-'+
		 ISNULL(FDADOSPGTO.DIGITOCONTA, '')+' - FAVORECIDO: '+
		 ISNULL(FDADOSPGTO.FAVORECIDO, '')
		 END	
from TMOV (NOLOCK)
INNER JOIN FLAN (NOLOCK) ON FLAN.IDMOV = TMOV.IDMOV AND FLAN.CODCOLIGADA = TMOV.CODCOLIGADA 
/*INNER JOIN TCPG (NOLOCK) ON TCPG.CODCPG = TMOV.CODCPG AND TCPG.CODCOLIGADA = TMOV.CODCOLIGADA
LEFT JOIN FDADOSPGTO (NOLOCK) ON TMOV.CODCFO = FDADOSPGTO.CODCFO*/
INNER JOIN FCFO ON FCFO.CODCFO = FLAN.CODCFO AND FLAN.CODCOLIGADA = FCFO.CODCOLIGADA 
INNER JOIN FDADOSPGTO (NOLOCK) ON FCFO.CODCFO = FDADOSPGTO.CODCFO AND FDADOSPGTO.CODCOLIGADA = FCFO.CODCOLIGADA
where 
TMOV.IDMOV = 179144 AND 
TMOV.CODCOLIGADA= 1

