select 
	FDADOSPGTO.DESCRICAO+' - '+FDADOSPGTO.NOMEAGENCIA+' - AG.: '+convert(VARCHAR,FDADOSPGTO.CODIGOAGENCIA)+'-'+FDADOSPGTO.DIGITOAGENCIA+' - CONTA: '+FDADOSPGTO.CONTACORRENTE+'-'+FDADOSPGTO.DIGITOCONTA+'. FAVORECIDO: '+FDADOSPGTO.FAVORECIDO,
	--TMOV.NUMEROMOV 'NUMEROMOV',
	--TMOV.FRETECIFOUFOB
	
from TMOV (NOLOCK)
INNER JOIN TCPG (NOLOCK) ON TCPG.CODCPG = TMOV.CODCPG AND TCPG.CODCOLIGADA = TMOV.CODCOLIGADA
LEFT JOIN FDADOSPGTO (NOLOCK) ON TMOV.CODCFO = FDADOSPGTO.CODCFO
where 
--TMOV.IDMOV = :IDMOV1 AND 
TMOV.CODCOLIGADA= 1
--group by tmov.NUMEROMOV, TCPG.NOME, TMOV.FRETECIFOUFOB, TMOV.CODCPG,
--TCPG.NOME,FDADOSPGTO.NOMEAGENCIA,FDADOSPGTO.CODIGOAGENCIA,FDADOSPGTO.DIGITOAGENCIA,FDADOSPGTO.CONTACORRENTE,FDADOSPGTO.DIGITOCONTA


SELECT * FROM FDADOSPGTO