SELECT * FROM MISMPRC WHERE IDPRJ=195 --COTAÇÃO DE VALOR DE INSUMOS

SELECT * FROM MISM WHERE IDPRJ=195 --INSUMO. CODISM é cod. a amostra para usuário. IDISM é o cod. principal do cadastro de insumo e que faz relações

SELECT * FROM MISMPRD WHERE IDPRJ=195 --VINCULO DE PRODUTO NO INSUMO

SELECT * FROM TPRDFIL WHERE IDPRD=5555 --ESTOCAVEL ENTRE AS COLIGADAS.

SELECT IDPRD, CODIGOPRD, NOMEFANTASIA, DTCADASTRAMENTO,USUARIOCRIACAO, DESCRICAO, * FROM TPRODUTO WHERE CODCOLPRD=2 order by 2 --CADASTRO DE PRODUTO

SELECT IDPRD, CODMOEPRECO1, DATABASEPRECO1, PRECO1, CODUNDCONTROLE, CODUNDCOMPRA, CODUNDVENDA, CODTB1FAT, CODTB3FAT,* FROM TPRODUTODEF WHERE CODCOLIGADA =1 --UNIDADE DO PRODUTO

/******************************* (OK) 1.1º PASSO - CADASTRO DE GRUPO DE CUSTOS DE/PARA ********************************************/
/*************************************************************************************/

SELECT CODCOLIGADA, IDPRJ, (SELECT 
		MAX(IDGIS) 
			FROM MGIS 
			WHERE CODCOLIGADA=1)+
			ROW_NUMBER() OVER(PARTITION BY CODGIS ORDER BY DESCGIS ASC) 'IDGIS',
	    CODGIS, DESCGIS, GRUPODNER, BDI, LEISOCIAL, 'mestre' 'RECCREATEDBY','2018-06-15' 'RECCREATEDON', 'mestre' 'RECMODIFIEDBY', '2018-06-15' 'RECMODIFIEDON'
FROM dbo.MGIS
WHERE CODCOLIGADA = 1 AND IDGIS = 1323 AND CODGIS = '27' AND IDPRJ=238 ???

----------------------
SELECT * FROM GAUTOINC WHERE CODAUTOINC='IDGIS'

----------------
(SELECT 
		MAX(IDGIS) 
			FROM MGIS 
			WHERE CODCOLIGADA=1)+
			ROW_NUMBER() OVER(PARTITION BY CODGIS ORDER BY DESCGIS ASC) 'IDGIS'
--------------
UPDATE dbo.GAUTOINC
SET VALAUTOINC = (SELECT MAX(IDGIS) FROM MGIS WHERE CODCOLIGADA = 1 AND IDPRJ=238)
WHERE CODCOLIGADA = 0 AND CODSISTEMA = 'M' AND CODAUTOINC = 'IDGIS'


/******************************* (OK) 1º PASSO - ENUMARAR DE FORMAR CORRETA O CODISM DOS INSUMOS FAZENDO UM DE/PARA, EM SEGUIDA APLICAR A QTD DE CARACTERES ********************************************/
/*************************************************************************************/

SELECT replicate('0',6-len(CODISM))+convert(varchar,CODISM) AS 'CODISM',CODISM, * 
FROM MISM 
WHERE 
IDPRJ= 195 --DEFINIR IDPRJ DO PROJ. MODELO. EX.: 195 --AND IDISM = 104822 ORDER BY 4 asc--AND CODISM=7342

---------------------REVERTER MUDANÇA--------------------------------

SELECT 
SUBSTRING(CODISM,PATINDEX('%[a-z,1-9]%',CODISM),LEN(CODISM)),*
--replicate('0',6-len(CODISM))+convert(varchar,CODISM) AS 'CODISM',CODISM, * 
FROM MISM 
WHERE 
IDPRJ= 195 ORDER BY 1


/*************************************************************************************/
/******************************* 2º PASSO - APLICAR O SET INDENTY PARA DESBLOQUEAR INSERT NA TAB TPRODUTOS E FAZER O INSERT *******************************/ 

--------------------------- INSERÇÃO DE INSUMOS ---------------------------
SELECT CODCOLIGADA, IDPRJ, IDISM, CODISM, DESCISM, CODUND, 'E''GRUPODNER', IDGIS, CODAPLIC, 0 'FATORK', CLIVREVALOR15, CLIVREVALOR16, 
0 'FLAGFRACIONARIO', 0 'JORNADA', 0 'PRAZORESSUP', 0 'PRIORIDADECALC', 0 'TIPO', 0 'TIPOISMDERIVADO', M 'APLICFORMULA', 0 'MINIMOHORAEXTRA', 0 'MAXIMOHORAEXTRA', 
0 'CUSTOUNITHORAEXTRA', 0 'JORNADAPERIODO', 0 'TIPOGERANECESSIDADE', 'mestre' 'RECCREATEDBY','2018-06-15' 'RECCREATEDON', 'mestre' 'RECMODIFIEDBY', '2018-06-15' 'RECMODIFIEDON', 0 'ISMDETALHADO'
FROM dbo.MISM
WHERE CODCOLIGADA = 1 AND IDPRJ = 238 AND IDISM = 134751 AND CODISM = '020078' AND DESCISM = 'PASTA LUBRIFICANTE PARA TUBOS E CONEXOES COM JUNTA ELASTICA (USO EM PVC, ACO, POLIETILENO E OUTROS) ( DE *400* G)' AND CODUND = 'UN' AND GRUPODNER = 'E' AND IDGIS = 1304 AND IDISMPRC IS NULL AND VALOR = 14,95 AND VALORSEMLEIS = 14,95 AND VALORIMPRODUTIVO = 0 AND CLIVREVALOR1 IS NULL AND CLIVREVALOR2 IS NULL AND CLIVREVALOR3 IS NULL AND CLIVREVALOR4 IS NULL AND CLIVREVALOR5 IS NULL AND CLIVREVALOR6 IS NULL AND CLIVREVALOR7 IS NULL AND CLIVREVALOR8 IS NULL AND CLIVREVALOR9 IS NULL AND IDPLAN IS NULL AND CODAPLIC = 'M' AND CUSTOHORVALORPROD IS NULL AND CUSTOHORVALORIMPROD IS NULL AND CLIVRE1 IS NULL AND CLIVRE2 IS NULL AND CLIVRE3 IS NULL AND CLIVRE4 IS NULL AND CLIVRE5 IS NULL AND CLIVREVALOR10 IS NULL AND CLIVREVALOR11 IS NULL AND CLIVREVALOR12 IS NULL AND CLIVREVALOR13 IS NULL AND CLIVREVALOR14 IS NULL AND FATORK = 0 AND CLIVREVALOR15 IS NULL AND CLIVREVALOR16 IS NULL AND CLIVREVALOR17 IS NULL AND CLIVREVALOR18 IS NULL AND CLIVREVALOR19 IS NULL AND CLIVREVALOR20 IS NULL AND CLIVREVALOR21 IS NULL AND CLIVREVALOR22 IS NULL AND CLIVREVALOR23 IS NULL AND CLIVREVALOR24 IS NULL AND CLIVREVALOR25 IS NULL AND CODEMOP IS NULL AND CODFGV IS NULL AND CODCPG IS NULL AND FLAGFRACIONARIO = 0 AND JORNADA = 0 AND CODPINI IS NULL AND PRAZORESSUP = 0 AND PRIORIDADECALC = 0 AND TIPO = 0 AND TIPOISMDERIVADO = 0 AND APLICFORMULA = 'M' AND FORMULAQTDE IS NULL AND FORMULAVALOR IS NULL AND FORMULAQTDECRONOG IS NULL AND MINIMOHORAEXTRA = 0 AND MAXIMOHORAEXTRA = 0 AND CUSTOUNITHORAEXTRA = 0 AND CODTBORCAMENTO IS NULL AND JORNADAPERIODO = 0 AND TIPOGERANECESSIDADE = 0 AND IMPRODUTIVIDADE IS NULL AND RECCREATEDBY = 'ESTTEIO' AND RECCREATEDON = '2017-08-17 17:47:53' AND RECMODIFIEDBY = 'ESTTEIO' AND RECMODIFIEDON = '2018-04-30 17:16:13' AND ISMDETALHADO = 0 AND CODCOLTBORCAMENTO IS NULL AND ARREDONDAQTDE IS NULL AND IDISMPINI IS NULL AND CODISMPINI IS NULL

--------------------------- INSERÇÃO DE COTAÇÃO ---------------------------
?????????????????????????? É PARA INSERIR
------------------------------------------

SELECT CODISM 'CODIGOPRD', DESCISM 'NOMEFANTASIA', DESCISM 'DESCRICAO'  --SELECT PARA UPDATE NO TPRODUTO
FROM MISM WHERE IDPRJ=195


SET IDENTITY_INSERT TPRODUTO on

INSERT INTO dbo.TPRODUTO (CODCOLPRD, IDPRD, CODIGOPRD, NOMEFANTASIA, TIPO, DESCRICAO, INATIVO, PESAVEL, DATAULTALTERACAO, CODUSUARIO, QTDEVOLUME, ID, RECMODIFIEDBY, RECMODIFIEDON)
SELECT 
0 'CODCOLPRD', 
(SELECT 
		MAX(IDPRD) 
			FROM TPRODUTO)+
			 ROW_NUMBER() OVER(ORDER BY CODISM ASC) 'IDPRD',
CODISM 'CODIGOPRD', 
SubString(DESCISM,1,75) 'NOMEFANTASIA',
(SELECT 
		MAX(CODIGOREDUZIDO) 
			FROM TPRODUTO)+
			 ROW_NUMBER() OVER(ORDER BY CODISM ASC) 'CODIGOREDUZIDO',
'P' 'TIPO', 
SubString(DESCISM,1,130) 'DESCRICAO', 
0 'INATIVO', 
0 'PESAVEL', 
CONVERT(VARCHAR, GETDATE(), 120) 'DATAULTALTERACAO', 
'mestre' 'CODUSUARIO', 
1 'QTDEVOLUME', 
(SELECT 
		MAX(IDPRD) 
			FROM TPRODUTO)+
			 ROW_NUMBER() OVER(ORDER BY CODISM ASC) 'ID',
'mestre' 'RECMODIFIEDBY', 
CONVERT(VARCHAR, GETDATE(), 120) 'RECMODIFIEDON'
FROM MISM WHERE IDPRJ= ??? --mudar aqui 195
/*******USAR CASO DÊ ERRO PARA IDENTIFICAR OS PRODUTOS QUE NÃO FORAM INSERIDOS******/
--AND NOT EXISTS
--(SELECT *
--FROM TPRODUTO WHERE  /*MUDAR ESTE CODIGO PARA O PROJ. MODELO*/
--TPRODUTO.CODIGOPRD = MISM.CODISM))

/*************************************************************************************/
/*ANTES DE RODAR O PASSO 3, IMPORTAR OS GRUPOS DE CUSTOS DO INSUMO PARA O CADASTRO TTB1 COM OS MESMOS CODIGOS*/
/******************************* 3º PASSO - FAZER O INSERT DOS IDPRD E CODISM NA TABELA TPRODUDEF*******************************/ 

SELECT
1 'CODCOLIGADA', A.IDPRD 'IDPRD', A.CODIGOPRD 'NUMNOFABRIC', 0 'PRECO1', 0 'PRECO2', 0 'PRECO3', 0 'PRECO4', 0 'PRECO5',
CONVERT(VARCHAR, GETDATE(), 120) 'DATABASEPRECO1', CONVERT(VARCHAR, GETDATE(), 120) 'DATABASEPRECO2', CONVERT(VARCHAR, GETDATE(), 120) 'DATABASEPRECO3', CONVERT(VARCHAR, GETDATE(), 120) 'DATABASEPRECO4', CONVERT(VARCHAR, GETDATE(), 120) 'DATABASEPRECO5', 'R$' 'CODMOEPRECO1',
B.CODUND 'CODUNDCONTROLE', B.CODUND 'CODUNDCOMPRA', B.CODUND 'CODUNDVENDA', 0 'CUSTOUNITARIO', B.IDGIS 'CODTB4FAT',  --COLOCAR GRUPO DE CUSTOS DO INSUMO AQUI'CODTAB1FAT',
0 'RECALCCUSTOMEDIO', 0 'CUSTOMEDIO',  
--0 'RECALCSALDO1', 0 'RECALCSALDO2', 0 'RECALCSALDO3', 0 'RECALCSALDO4', 0 'RECALCSALDO5', 0 'RECALCSALDO6', 0 'RECALCSALDO7', 0 'RECALCSALDO8', 0 'RECALCSALDO9', 0 'RECALCSALDO10',
'mestre' 'RECCREATEDBY', CONVERT(VARCHAR, GETDATE(), 120)  'RECCREATEDON','mestre' 'RECMODIFIEDBY', CONVERT(VARCHAR, GETDATE(), 120) 'RECMODIFIEDON', 1 'PRODVISIVELCLICBUSINESS'
FROM
(SELECT IDPRD, CODIGOPRD
FROM tproduto 
WHERE 
	NOT EXISTS (SELECT * FROM TPRODUTODEF WHERE TPRODUTODEF.IDPRD = TPRODUTO.IDPRD) AND CODCOLPRD=0) A
INNER JOIN
(SELECT CODISM, CODUND, IDGIS
FROM MISM WHERE IDPRJ=238 /*MUDAR ESTE CODIGO PARA O PROJ. MODELO*/) 
B ON A.CODIGOPRD = B.CODISM


/*************************************************************************************/
/******************************* 4º PASSO - FAZER O INSERT DE FILIAIS DE ESTOQUE*******************************/ 
/******************************* OBS.: QUANDO GERAR OS INSERTS MUDAR A TABELA DO INSERT PARA TPRDFIL*******************************/ 

SELECT
    T.IDPRD,
    F.CODCOLIGADA, 
    F.CODFILIAL, 
    F.PRECO, 
    1 'ESTOCAVEL', 
    0 'CONSIGNADO', 
    'mestre' 'RECCREATEDBY', 
    CONVERT(VARCHAR, GETDATE(), 120) 'RECCREATEDON', 
    'mestre' 'RECMODIFIEDBY', 
    CONVERT(VARCHAR, GETDATE(), 120) 'RECMODIFIEDON'
FROM TPRODUTO AS T
CROSS JOIN TPRDFIL AS F
WHERE
    T.CODCOLPRD = 0 AND
    LEN(T.IDPRD) = 5 AND
    F.CODCOLIGADA = 1 AND 
    F.IDPRD = 49470
    --AND T.IDPRD=54629

/*************************************************************************************/
/******************************* 5º PASSO - ATUALIZAR AS TABELAS RELACIONADAS DE AUTO INCREMENTO.*******************************/ 

UPDATE dbo.GAUTOINC
SET VALAUTOINC = (SELECT MAX(IDPRD) FROM TPRODUTO)
WHERE CODAUTOINC = 'IDPRD'

UPDATE dbo.GAUTOINC
SET VALAUTOINC = (SELECT MAX(CODIGOREDUZIDO) FROM TPRODUTO WHERE CODCOLPRD=0)
WHERE CODAUTOINC = 'CODIGOREDUZIDO' AND CODCOLIGADA=0

--SELECT * FROM GAUTOINC WHERE VALAUTOINC='ID'


/*************************************************************************************/
/******************************* 6º PASSO - VINCULAR O PRODUTO AO INSUMO*******************************/ 

SELECT 1 'CODCOLIGADA', A.IDPRJ, A.IDISM, B.IDPRD, 1 'PRINCIPAL', 
'mestre' 'RECCREATEDBY', getdate() 'RECCREATEDON', 'mestre' 'RECMODIFIEDBY', getdate() 'RECMODIFIEDON'
FROM
(SELECT CODISM, IDPRJ, IDISM FROM MISM) --WHERE IDISM=119621) 
A INNER JOIN
(SELECT CODIGOPRD, IDPRD  FROM TPRODUTO) --WHERE IDPRD=54629) 
B ON A.CODISM = B.CODIGOPRD
WHERE
A.IDPRJ=??? --TROCAR IDPRD DO PROJETO MODELO ATUAL 195

/*************************************************************************************/
/******************************* OUTROS - INCLUSÃO DE GRUPO DE CUSTOS PARA GLOBAL*******************************/ 


SELECT CODCOLIGADA, 0 'IDPRJ', 
(SELECT 
		MAX(IDGIS) 
			FROM MGIS)+
			 ROW_NUMBER() OVER(ORDER BY DESCGIS ASC) 'IDGIS', 
CODGIS, DESCGIS, GRUPODNER, BDI, LEISOCIAL, PERCSOBREGRPDNER, CODISMINI, CODISMFIM, CODUNDDEFAULT, CODCPG, JORNADA, PRAZORESSUP, EQUALIZAVEL, CODTBORCAMENTO, 'mestre' 'RECCREATEDBY', RECCREATEDON, 'mestre' 'RECMODIFIEDBY', RECMODIFIEDON, CODCOLTBORCAMENTO, IDGISPINI
FROM MGIS a WHERE IDPRJ=238 AND
NOT EXISTS (SELECT * FROM MGIS b WHERE B.IDPRJ=0 AND b.codgis = a.codgis)
--AND YEAR(RECCREATEDON)='2018'

-----------------------------------------------


UPDATE dbo.GAUTOINC
SET VALAUTOINC = (SELECT MAX(IDGIS) FROM MGIS)
WHERE CODCOLIGADA = 0 AND CODSISTEMA = 'M' AND CODAUTOINC = 'IDGIS'
GO

/******************************* INCLUSÃO DE INSUMOS PARA GLOBAL*******************************/ 
SELECT 
CODCOLIGADA, 0 'IDPRJ', 
(SELECT 
		MAX(IDISM) 
			FROM MISM)+
			 ROW_NUMBER() OVER(ORDER BY CODISM ASC) 'IDISM',
CODISM, DESCISM, CODUND, GRUPODNER, 
CASE
WHEN idgis =1374 THEN 1432
WHEN idgis =1377 THEN 1438
WHEN idgis =1369 THEN 1442
WHEN idgis =1375 THEN 1434
WHEN idgis =1321 THEN 1302
WHEN idgis =1372 THEN 1435
WHEN idgis =1378 THEN 1433
WHEN idgis =1376 THEN 1440
WHEN idgis =1373 THEN 1431
WHEN idgis =1304 THEN 1285
WHEN idgis =1370 THEN 1437
WHEN idgis =1371 THEN 1436
WHEN idgis =1368 THEN 1439
END 'IDGIS', IDISMPRC, VALOR, VALORSEMLEIS, VALORIMPRODUTIVO, CLIVREVALOR1, CLIVREVALOR2, CLIVREVALOR3, CLIVREVALOR4, CLIVREVALOR5, CLIVREVALOR6, CLIVREVALOR7, CLIVREVALOR8, CLIVREVALOR9, IDPLAN, CODAPLIC, CUSTOHORVALORPROD, CUSTOHORVALORIMPROD, CLIVRE1, CLIVRE2, CLIVRE3, CLIVRE4, CLIVRE5, CLIVREVALOR10, CLIVREVALOR11, CLIVREVALOR12, CLIVREVALOR13, CLIVREVALOR14, FATORK, CLIVREVALOR15, CLIVREVALOR16, CLIVREVALOR17, CLIVREVALOR18, CLIVREVALOR19, CLIVREVALOR20, CLIVREVALOR21, CLIVREVALOR22, CLIVREVALOR23, CLIVREVALOR24, CLIVREVALOR25, CODEMOP, CODFGV, CODCPG, FLAGFRACIONARIO, JORNADA, CODPINI, PRAZORESSUP, PRIORIDADECALC, TIPO, TIPOISMDERIVADO, APLICFORMULA, FORMULAQTDE, FORMULAVALOR, FORMULAQTDECRONOG, MINIMOHORAEXTRA, MAXIMOHORAEXTRA, CUSTOUNITHORAEXTRA, CODTBORCAMENTO, JORNADAPERIODO, TIPOGERANECESSIDADE, IMPRODUTIVIDADE, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON, ISMDETALHADO, CODCOLTBORCAMENTO, ARREDONDAQTDE, IDISMPINI, CODISMPINI
FROM MISM  B
WHERE 
IDPRJ = 238 AND 
CODCOLIGADA=1 AND
NOT EXISTS (SELECT * FROM MISM A WHERE IDPRJ=0 AND A.CODISM = B.CODISM )

-----------------------------------------------


UPDATE dbo.GAUTOINC
SET VALAUTOINC = (SELECT MAX(IDISM) FROM MISM)
WHERE CODCOLIGADA = 0 AND CODSISTEMA = 'M' AND CODAUTOINC = 'IDISM'
GO

/*************************************************************************************/
/******************************* OUTROS - INCLUSÃO DE GRUPO DE CUSTOS PARA GLOBAL*******************************/ 



/******************************* BASE DE AUTOINCREMENTO ********************************************/
--(SELECT 
--		MAX(IDPRD) 
--			FROM TPRODUTO 
--			WHERE CODCOLIGADA=0)+
--			ROW_NUMBER() OVER(PARTITION BY SET5.IDPERLET ORDER BY SET5.RA ASC) 'IDOCORALUNO',



/******************************* ATUALIZA GAUTOINC ********************************************/
--UPDATE dbo.GAUTOINC
--SET VALAUTOINC = (SELECT MAX(IDPRD) FROM TPRODUTODEF)
--WHERE CODCOLIGADA = 0 AND CODSISTEMA = 'T' AND CODAUTOINC = 'IDPRD'
--GO




