SELECT TLOC.CODCOLIGADA, TLOC.CODFILIAL, TLOC.CODLOC+' - '+TLOC.NOME 'LOCAL_ESTOQUE', TPRD.CODIGOPRD, TPRDLOC.IDPRD, TPRD.DESCRICAO, 
TPRDLOC.SALDOFISICO2,
TPRDLOC.CUSTOMEDIO, TPRDLOC.SALDOFINANCEIRO2
FROM TLOC
INNER JOIN GFILIAL ON GFILIAL.CODCOLIGADA = TLOC.CODCOLIGADA AND GFILIAL.CODFILIAL = TLOC.CODFILIAL
INNER JOIN TPRDLOC ON TPRDLOC.CODCOLIGADA = TLOC.CODCOLIGADA AND TPRDLOC.CODFILIAL = TLOC.CODFILIAL AND TPRDLOC.CODLOC = TLOC.CODLOC
INNER JOIN TPRD ON TPRD.IDPRD = TPRDLOC.IDPRD AND TPRD.CODCOLIGADA = TPRDLOC.CODCOLIGADA
WHERE
GFILIAL.CODFILIAL=1
AND TLOC.CODCOLIGADA=4
AND TPRDLOC.SALDOFISICO2 <> 0
ORDER BY TPRD.CODIGOPRD
