SELECT  IDMOV,
		COALESCE(
		(SELECT CAST(CONVERT(VARCHAR, DATAVENCIMENTO, 103)+', R$ '+convert(varchar, VALORORIGINAL)+', '+
	CASE 
		WHEN STATUSLAN = 0 THEN 'Em aberto'
		WHEN STATUSLAN = 1 THEN 'Quitado'
		WHEN STATUSLAN = 2 THEN 'Cancelado'
	END AS VARCHAR(800)) + ' | ' AS [text()]
		 FROM FLAN AS O
		 WHERE 
			IDMOV = 107314
			AND CODCOLIGADA=1
		 ORDER BY 1
		 FOR XML PATH(''), TYPE).value('.[1]', 'VARCHAR(MAX)'), '') AS Produtos
FROM FLAN AS C
WHERE 
			IDMOV = 107314
			AND CODCOLIGADA=1
GROUP BY IDMOV