with CTE_Origem as
(
SELECT DISTINCT C.CODCOLIGADA, C.IDPRD, --C.CODIGOPRD, 
--C.DESCRICAO, 
C.CODUND, C.BASE_MOV,  C.CODUNDCONTROLE, C.CODUNDBASE,
--C.CODUNDCOMPRA,  
--C.CODUNDCONTROLE, C.CODUNDVENDA, 
C.IDMOV, C.CODTMV
--C.BASE_MOV, C.BASE_PROD
FROM
(SELECT DISTINCT
B.CODCOLIGADA, B.IDPRD, B.CODIGOPRD, B.DESCRICAO, A.CODUND, B.CODUNDCOMPRA, B.CODUNDCONTROLE, 
B.CODUNDVENDA, A.IDMOV, A.CODTMV, C1.CODUNDBASE, A.BASE_MOV
--, A.BASE_MOV, B.BASE_PROD
FROM 
(select TITMMOV.CODUND, TITMMOV.IDPRD, TITMMOV.NSEQITMMOV, TMOV.CODCOLIGADA, TMOV.IDMOV, TMOV.CODTMV, TMOV.STATUS, TMOV.DATAEMISSAO
, TUND.CODUNDBASE  'BASE_MOV'
from 
	TITMMOV 
	INNER JOIN TMOV ON TMOV.IDMOV = TITMMOV.IDMOV AND TMOV.CODCOLIGADA=TITMMOV.CODCOLIGADA
	INNER JOIN TUND ON TUND.CODUND = TITMMOV.CODUND
WHERE 
	TMOV.CODCOLIGADA IN (1,2,3,4)) A, 
(select 
TPRODUTO.CODIGOPRD, TPRODUTO.DESCRICAO, TPRODUTO.IDPRD, TPRODUTODEF.CODUNDCOMPRA,TPRODUTODEF.CODUNDCONTROLE,TPRODUTODEF.CODUNDVENDA, TPRODUTODEF.CODCOLIGADA
--,TUND.CODUNDBASE 'BASE_PROD'
from 
	TPRODUTODEF 
	INNER JOIN TPRODUTO ON TPRODUTO.IDPRD = TPRODUTODEF.IDPRD 
	--INNER JOIN TUND ON TUND.CODUND = TPRODUTODEF.CODUNDCONTROLE
	
WHERE CODCOLIGADA IN (1,2,3,4)) B,

(SELECT CODUND, DESCRICAO, CODUNDBASE FROM TUND) C1
WHERE
A.CODUND <> B.CODUNDCOMPRA
AND A.IDPRD = B.IDPRD
AND A.CODCOLIGADA = B.CODCOLIGADA
AND B.CODUNDCONTROLE = C1.CODUND
AND YEAR(A.DATAEMISSAO) IN ('2018')
AND A.CODTMV IN ('1.1.01', '1.1.06', '1.1.02', '1.1.03')
--AND A.CODTMV IN ('1.2.20')--,'4.1.01','4.1.03','1.2.10','2.2.10','4.1.02')
AND A.STATUS = 'a'
) C
WHERE
C.BASE_MOV <> C.CODUNDBASE
)
update t
set t.CODUND = o.CODUNDCONTROLE
from TITMMOV as t
inner join CTE_Origem as o
   on o.IDPRD = t.IDPRD 
    and o.idmov = t.IDMOV 
    and o.CODCOLIGADA = t.CODCOLIGADA