SELECT  IDMOV,
		COALESCE(
		(SELECT CAST(CONVERT(VARCHAR, DATAVENCIMENTO, 103)+', R$ '+convert(varchar, VALORORIGINAL)+', '+
	CASE 
		WHEN STATUSLAN = 0 THEN 'Em aberto'
		WHEN STATUSLAN = 1 THEN 'Quitado'
		WHEN STATUSLAN = 2 THEN 'Cancelado'
	END AS VARCHAR(800)) + ' | '
		 FROM FLAN AS O
		 WHERE 
			IDMOV= :IDMOV
			AND CODCOLIGADA = :CODCOLIGADA
		 ORDER BY 1
		FOR XML PATH(''), TYPE), ''
		) AS Produtos
FROM FLAN AS C
WHERE 
			IDMOV= :IDMOV
			AND CODCOLIGADA = :CODCOLIGADA
GROUP BY IDMOV