SELECT DISTINCT A.RA, A.CODCONTRATO, B.PARCELA, B.VALOR 'VL-BRUTO', E.CODPERLET,
CASE 
	WHEN C.TIPODESC='P' THEN B.VALOR - (B.VALOR * (C.DESCONTO/100))
	WHEN C.TIPODESC='V' THEN (B.VALOR - C.DESCONTO)
END 'VL-LIQUIDO' ,
C.TIPODESC,
CASE 
	WHEN C.TIPODESC='P' THEN ( (C.DESCONTO / 100) * B.VALOR)
	WHEN C.TIPODESC='V' THEN C.DESCONTO
END 'VL-BOLSA'
 --,D.NOME '%BOLSA'
FROM SCONTRATO A
INNER JOIN SPLETIVO E ON E.CODCOLIGADA = A.CODCOLIGADA AND E.IDPERLET = A.IDPERLET
INNER JOIN SPARCELA B ON A.CODCOLIGADA = B.CODCOLIGADA AND A.RA = B.RA AND A.CODCONTRATO = B.CODCONTRATO AND A.IDPERLET = B.IDPERLET
LEFT JOIN SBOLSAALUNO C ON A.CODCOLIGADA = C.CODCOLIGADA AND A.RA = C.RA AND A.CODCONTRATO = C.CODCONTRATO AND A.IDPERLET = C.IDPERLET
--INNER JOIN SBOLSA D ON D.CODCOLIGADA=C.CODCOLIGADA AND D.CODBOLSA=C.CODBOLSA

WHERE
C.ATIVA='S'
AND A.RA='0000138'
AND E.CODPERLET='2019-1'
AND B.PARCELA=1

SELECT * FROM SBOLSAALUNO WHERE RA='0000138' AND IDPERLET=403



SELECT * FROM SPARCELA WHERE RA='0000138'

SELECT * FROM SBOLSA


--SELECT * FROM GLINKSREL WHERE MASTERTABLE='SBOLSA' AND CHILDTABLE='STURMADISC'