/*
1º ANTES DE RODAR O WITH AS, RODAR CONSULTA E GERAR OS UPDATES SEPARADOS NO SQL DBX PARA ASSIM QUE FOR GERADO TROCAR A TABELA TMOV PELA TMOVRATCCU E EM SEGUIDA ESPERAR...
NÃO EXECUTAR AINDA*/
SELECT DISTINCT D.PERCENTUAL,  A.IDLAN, A.CODCCUSTO, D.CODCCUSTO, A.CODCOLIGADA
FROM  FLAN A 
INNER JOIN FLANRATCCU D ON D.IDLAN = A.IDLAN AND D.CODCOLIGADA = A.CODCOLIGADA
WHERE
d.PERCENTUAL = 100
and A.CODCCUSTO <> D.CODCCUSTO
AND YEAR(A.DATACRIACAO)=2018


/*
2º RODAR CONSULTA ASSIM QUE GERAR OS UPDATES DA 1ª ETAPA
*/

with CTE_Origem as
(
SELECT A.DATACRIACAO,A.CODCOLIGADA, A.IDLAN, A.CODCCUSTO 'FLAN_FLAN', D.CODCCUSTO 'FLAN_RAT', 
D.PERCENTUAL
FROM FLAN A 
INNER JOIN FLANRATCCU D ON D.IDLAN = A.IDLAN AND D.CODCOLIGADA = A.CODCOLIGADA
WHERE
--C.PERCENTUAL <> 100
--and 
d.PERCENTUAL = 100
and A.CODCCUSTO <> D.CODCCUSTO
AND YEAR(A.DATACRIACAO)=2018
) 
update t
set t.CODCCUSTO = o.FLAN_FLAN
from FLANRATCCU as t
inner join CTE_Origem as o
    on o.IDLAN = t.IDLAN 
    and o.CODCOLIGADA = t.CODCOLIGADA

/*
3º RODAR OS UPDATES
*/
