
SELECT A.IDMOV, 
    COALESCE(
                 (SELECT CAST(C.CODTRF + ' - ' + C.NOME AS VARCHAR(800))+ ' / ' FROM TITMMOV A
       INNER JOIN TITMMOVRATCCU B
         ON B.CODCOLIGADA = A.CODCOLIGADA
            AND B.IDMOV = A.IDMOV
            AND B.NSEQITMMOV = A.NSEQITMMOV
       LEFT JOIN MTAREFA C
         ON C.CODCOLIGADA = B.CODCOLIGADA
            AND C.IDPRJ = B.IDPRJ
            AND C.IDTRF = B.IDTRF
WHERE  A.IDMOV = 54177
       AND A.IDPRD = 14879
       AND TMOV.CODCCUSTO = '1.1053'  ORDER BY 1
		FOR XML PATH(''), TYPE), ''
               ) 'TAREFA',
                A.IDPRD 'IDPRD1',
                A.IDMOV 'IDMOV1',
                TMOV.CODTMV,
                B.PERCENTUAL,
				A.CODCOLIGADA 'CODCOLIGADA1',
				TMOV.CODCCUSTO 'CODCCUSTO1'
FROM   TITMMOV A
       INNER JOIN TMOV
         ON TMOV.CODCOLIGADA = A.CODCOLIGADA
            AND TMOV.IDMOV = A.IDMOV
       INNER JOIN TITMMOVRATCCU B
         ON B.CODCOLIGADA = A.CODCOLIGADA
            AND B.IDMOV = A.IDMOV
            AND B.NSEQITMMOV = A.NSEQITMMOV
       LEFT JOIN MTAREFA C
         ON C.CODCOLIGADA = B.CODCOLIGADA
            AND C.IDPRJ = B.IDPRJ
            AND C.IDTRF = B.IDTRF
WHERE  A.IDMOV = 54177
       AND A.IDPRD = 14879
       AND TMOV.CODCCUSTO = '1.1053'
GROUP BY A.IDMOV,
A.IDPRD,
                A.IDMOV,
                TMOV.CODTMV,
                B.PERCENTUAL,
				A.CODCOLIGADA,
				TMOV.CODCCUSTO