SELECT A.CODPRJ, UPPER(A.PROJETO) 'PROJETO',A.VALOR, UPPER(A.TAREFA) 'TAREFA',A.GRUPODNER, A.GRUPODNER1, B.IDPERIODO, CONVERT(VARCHAR,B.PERCPLANEJADO)+'%' 'PERCENTUALPLANEJADO', 
/*CONVERT(decimal(6,4), 9.5) AS decimal; 
CONVERT(decimal(10,2), B.PERCPLANEJADO) 'PERCENTUALPLANEJADO', CONVERT(decimal(10,2), A.VALOR) '',*/
(A.VALOR*B.PERCPLANEJADO)/100 'VAL-PLAN-POR-PERIODO', B.DTINICIO 'INICIO', DTFIM 'FIM'
FROM
(	SELECT ROUND(SUM(MABCISMTRF.VALOR + MABCISMTRF.VALORIMPRODUTIVO),2) VALOR,  MTAREFA.CODTRF 'CODTRF1',
	MTAREFA.CODTRF+' - '+MTAREFA.DESCRICAO 'TAREFA',
       MTAREFA.CODTRF,
       MISM.GRUPODNER,
	   MTAREFA.IDPRJ,
	   MTAREFA.IDTRF, MPRJ.CODPRJ, MPRJ.CODCOLIGADA,
	   MPRJ.CODPRJ+' - '+MPRJ.DESCRICAO 'PROJETO',
	   CASE WHEN MISM.GRUPODNER = 'A' THEN 'EQUIPAMENTOS'
		WHEN MISM.GRUPODNER = 'B' THEN 'MÃO DE OBRA'
		WHEN MISM.GRUPODNER = 'C' THEN 'MATERIAIS'
		WHEN MISM.GRUPODNER = 'D' THEN 'ATIVIDADES AUXILIARES'
		WHEN MISM.GRUPODNER = 'E' THEN 'TEMPO FIXO'
		WHEN MISM.GRUPODNER = 'F' THEN 'MOMENTOS DE TRANSPORTE'
		WHEN MISM.GRUPODNER = 'N' THEN 'NENHUM'
		END 'GRUPODNER1'
FROM   MABCISMTRF (NOLOCK),
       MISM (NOLOCK),
       MTAREFA (NOLOCK),
	   MPRJ (NOLOCK)
WHERE  MABCISMTRF.CODCOLIGADA = 1
       AND MABCISMTRF.IDPRJ = 11
       AND MABCISMTRF.IDCENARIO = 0
       AND MABCISMTRF.TIPOPLANILHA = 0
       AND MABCISMTRF.IDISM = MISM.IDISM
       AND MABCISMTRF.IDOBRA = MTAREFA.IDTRF
       AND MABCISMTRF.CODCOLIGADA = MISM.CODCOLIGADA
       AND MABCISMTRF.IDPRJREC = MISM.IDPRJ
       AND MABCISMTRF.CODCOLIGADA = MTAREFA.CODCOLIGADA
       AND MABCISMTRF.IDPRJ = MTAREFA.IDPRJ

	   AND MABCISMTRF.CODCOLIGADA = MPRJ.CODCOLIGADA
       AND MABCISMTRF.IDPRJREC = MPRJ.IDPRJ

       --AND MISM.GRUPODNER = 'B'
       --AND MTAREFA.CODTRF = '002.02.002.001'
	  -- AND MTAREFA.CODTRF = '002.02.001.001'
GROUP  BY MTAREFA.CODTRF,
          MISM.GRUPODNER,
		  MTAREFA.CODCOLIGADA, MPRJ.DESCRICAO, MPRJ.CODCOLIGADA,
	   MTAREFA.IDPRJ, MTAREFA.DESCRICAO, MPRJ.CODPRJ,
	   MTAREFA.IDTRF ) A
INNER JOIN
(
 select IDPRJ, CODCOLIGADA, IDPERIODO, IDTRF, PERCPLANEJADO, DTINICIO, DTFIM from MXMTRFCRONOG where IDPRJ=11 AND PERCPLANEJADO is not null 
) B
ON B.IDTRF = A.IDTRF AND
	B.CODCOLIGADA = A.CODCOLIGADA AND
	B.IDPRJ = A.IDPRJ
WHERE
A.CODPRJ= 001
AND IDPERIODO BETWEEN 1 AND 16
AND A.TAREFA IS NOT NULL
ORDER BY A.TAREFA


	--SELECT * FROM MPRJ