DELETE FROM MCNT WHERE IDPRJ=11
DELETE FROM MTRFMED WHERE IDPRJ=11 
DELETE FROM MITMCNT WHERE IDPRJ=11 
DELETE FROM MTRFPRC WHERE IDPRJ=11 
DELETE FROM MPDO WHERE IDPRJ=11 
DELETE FROM MPDODETRET WHERE IDPRJ=11 
DELETE FROM MCNTPDOOBS WHERE IDPRJ=11
DELETE FROM MCNTPDOMOV WHERE IDPRJ=11  
DELETE FROM MPDOCOMPL WHERE IDPRJ=11 
DELETE FROM MCNTCOMPL WHERE IDPRJ=11 
DELETE FROM MCNTOBS WHERE IDPRJ=11 
DELETE FROM MCNTSTATUSLOG WHERE IDPRJ=11 
DELETE FROM MOBJCNT WHERE IDPRJ=11
DELETE FROM MOBJCNTMED WHERE IDPRJ=11

