SELECT DISTINCT 
	B.PROJETO,
	B.TAREFA, 
	--C.CONTRATO,
	B.COMPOSIÇÃO,
	A.PRODUTO,
	B.VALOR,
	A.PRECOUNITARIO,
	VALOR_TOTAL,
	A.IDMOV,
	A.HISTORICOCURTO,
	A.HISTORICO_GERAL,
	A.Nº_PEDIDO,
	A.NFE,
	A.FORNECEDOR
FROM
(
SELECT DISTINCT
	A.CODCOLIGADA,
	A.IDPRJ,
	D.DESCRICAO 'PRODUTO', 
	A.QUANTIDADE, 
	A.PRECOUNITARIO, 
	A.QUANTIDADE * A.PRECOUNITARIO 'VALOR_TOTAL',
	A.IDMOV,
	A.IDPRD,
	A1.IDTRF,
	A2.HISTORICOCURTO,
	B2.HISTORICOCURTO 'HISTORICO_GERAL',
	B.NUMEROMOV 'NFE',
	B.SEGUNDONUMERO 'Nº_PEDIDO',
	B1.NOMEFANTASIA 'FORNECEDOR'
FROM TITMMOV A
	 INNER JOIN TMOV B ON A.CODCOLIGADA = B.CODCOLIGADA AND A.CODFILIAL = B.CODFILIAL AND A.IDMOV = B.IDMOV
	 LEFT JOIN FLAN C ON  B.CODCOLIGADA = C.CODCOLIGADA AND C.CODFILIAL = B.CODFILIAL  AND C.IDMOV = B.IDMOV
	 INNER JOIN TPRD D ON D.IDPRD = A.IDPRD AND A.CODCOLIGADA = C.CODCOLIGADA
	 INNER JOIN TITMMOVRATCCU A1 ON A.CODCOLIGADA = A1.CODCOLIGADA AND A.IDMOV = A1.IDMOV
	 LEFT JOIN TITMMOVHISTORICO A2 ON A2.IDMOV = A.IDMOV AND A2.NSEQITMMOV = A.NSEQITMMOV AND A2.CODCOLIGADA = A.CODCOLIGADA
	 LEFT JOIN TMOVHISTORICO B2 ON B2.IDMOV = B.IDMOV AND B2.CODCOLIGADA = B.CODCOLIGADA
	 INNER JOIN FCFO B1 ON B1.CODCFO = B.CODCFO AND B1.CODCOLIGADA = B.CODCOLIGADA
WHERE
	A.IDPRJ=8
) 
	A LEFT JOIN
(
SELECT DISTINCT
	G.CODCOLIGADA,
	G.IDPRJ,
	G.CODPRJ+' - '+G.DESCRICAO 'PROJETO', 
	E.CODTRF+' - '+E.DESCRICAO 'TAREFA', 
	L.CODCMP+' - '+L.DESCCMP 'COMPOSIÇÃO',
	H.VALOR,
	H1.IDPRD,
	--F1.IDMOV,
	E.IDTRF
FROM
	MPRJ G
	INNER JOIN MTAREFA E ON G.CODCOLIGADA = E.CODCOLIGADA AND G.IDPRJ = E.IDPRJ --AND G.IDTRF = E.IDTRF
 
	LEFT JOIN MCMP L ON L.IDPRJ = G.IDPRJ AND E.IDCMP = L.IDCMP AND E.CODCOLIGADA = L.CODCOLIGADA  
	LEFT JOIN MRECCMP J ON J.IDCMP = L.IDCMP AND L.CODCOLIGADA = J.CODCOLIGADA AND J.IDPRJ = L.IDPRJ
	
	LEFT JOIN MISM H ON H.CODCOLIGADA = J.CODCOLIGADA AND H.IDISM = J.IDISM AND H.IDPRJ = J.IDPRJ
	LEFT JOIN MISMPRD H1 ON H1.CODCOLIGADA = J.CODCOLIGADA AND H1.IDISM = J.IDISM AND H1.IDPRJ = L.IDPRJ

	--LEFT JOIN MCNTPDOMOV F1 ON G.CODCOLIGADA=F1.CODCOLIGADA AND G.IDPRJ=F1.IDPRJ --AND A1.IDMOV= F1.IDMOV
	--LEFT JOIN MCNT F ON G.CODCOLIGADA=F.CODCOLIGADA AND G.IDPRJ=F.IDPRJ AND F1.IDCNT=F.IDCNT
WHERE
	G.IDPRJ=8
	AND E.SERVICO=1
) 
B ON 
	A.IDPRJ = B.IDPRJ AND 
	A.CODCOLIGADA = B.CODCOLIGADA AND 
	A.IDPRD = B.IDPRD AND
	--A.IDMOV = B.IDMOV AND 
	A.IDTRF = B.IDTRF
WHERE
	B.TAREFA IS NOT NULL





--LEFT JOIN
--(
--SELECT 
--	F.CODCOLIGADA,
--	F.IDPRJ,
--	F.NUMCNT+' - '+F.COMENTARIO 'CONTRATO',
--	F1.IDMOV
--FROM MCNT F
--	INNER JOIN MCNTPDOMOV F1 ON F.CODCOLIGADA=F1.CODCOLIGADA AND F.IDPRJ=F1.IDPRJ
--) C ON
--	A.IDMOV = C.IDMOV AND
--	A.IDPRJ = C.IDPRJ AND
--	A.CODCOLIGADA = C.CODCOLIGADA

	--SELECT * FROM TPRODUTO WHERE DESCRICAO LIKE '%PRESTAÇÃO%'


 --AND B.CODTMV LIKE '1.1.0%'
 --AND L.CODCMP='MR10823'
 --AND A.IDMOV=176493
 --AND C.PAGREC=2 --apagar


 --SELECT * FROM MRECCMP WHERE IDPRJ=8 AND IDCMP=328 AND IDISM=605
 --SELECT * FROM MISMPRD WHERE IDPRJ=8

 --SELECT * FROM MCNTPDOMOV WHERE IDPRJ=8

 /*
 MPRJ - PROJETO
 MTAREFA - TAREFA
 MCMP - COMPOSIÇÃO
 MISM - INSUMO
 MISMPRC - PREÇO DO INSUMO
 MCNT - CONTRATO
 MCNTPDOMOV - VINCULO DO PERIODO COM TMOV

 */