 SELECT DISTINCT 
 --C.PAGREC,
 --G.IDPRJ 'COD_PROJETO', 
 G.CODPRJ+' - '+G.DESCRICAO 'PROJETO', 
 E.CODTRF+' - '+E.DESCRICAO 'TAREFA', 
 F.NUMCNT+' - '+F.COMENTARIO 'CONTRATO',
 L.CODCMP+' - '+L.DESCCMP 'COMPOSIÇÃO',
 D.DESCRICAO 'PRODUTO', 
 --H.VALOR 'VL_COT_PRJ',
 A.QUANTIDADE, 
 --A.PRECOUNITARIO, 
 A1.VALOR, 
 A.QUANTIDADE * A1.VALOR 'VALOR_TOTAL'
 FROM TITMMOV A
 INNER JOIN TMOV B ON A.CODCOLIGADA = B.CODCOLIGADA AND A.CODFILIAL = B.CODFILIAL AND A.IDMOV = B.IDMOV
 LEFT JOIN FLAN C ON  B.CODCOLIGADA = C.CODCOLIGADA AND C.CODFILIAL = B.CODFILIAL  AND C.IDMOV = B.IDMOV --AND C.IDMOV = A.IDMOV
 INNER JOIN TPRD D ON D.IDPRD = A.IDPRD AND A.CODCOLIGADA = C.CODCOLIGADA

 INNER JOIN TITMMOVRATCCU A1 ON A.CODCOLIGADA = A1.CODCOLIGADA AND A.IDMOV = A1.IDMOV --AND A1.VALOR= SUM(A1.VALOR) --AND A.NSEQITMMOV = A1.NSEQITMMOV
 
 INNER JOIN MPRJ G ON A.CODCOLIGADA = G.CODCOLIGADA AND A1.IDPRJ = G.IDPRJ --AND A.CODFILIAL = G.CODFILIAL
 INNER JOIN MTAREFA E ON A.CODCOLIGADA = E.CODCOLIGADA AND G.IDPRJ = E.IDPRJ AND A1.IDTRF = E.IDTRF
 
 LEFT JOIN MCMP L ON L.IDPRJ = A1.IDPRJ AND E.IDCMP = L.IDCMP AND E.CODCOLIGADA = L.CODCOLIGADA  
 LEFT JOIN MRECCMP J ON J.IDCMP = L.IDCMP AND L.CODCOLIGADA = J.CODCOLIGADA AND J.IDPRJ = L.IDPRJ
 LEFT JOIN MISM H ON H.CODCOLIGADA = J.CODCOLIGADA AND H.IDISM = J.IDISM AND H.IDPRJ = L.IDPRJ
 --LEFT JOIN MISMPRC I ON H.CODCOLIGADA = I.CODCOLIGADA AND H.IDISM = I.IDISM AND H.IDPRJ = I.IDPRJ AND PRECOUNITARIO=1

 LEFT JOIN MCNTPDOMOV F1 ON A1.CODCOLIGADA=F1.CODCOLIGADA AND A1.IDPRJ=F1.IDPRJ AND A1.IDMOV= F1.IDMOV
 LEFT JOIN MCNT F ON F1.CODCOLIGADA=F.CODCOLIGADA AND F1.IDPRJ=F.IDPRJ AND F1.IDCNT=F.IDCNT

 --CODCOLIGADA,IDPRJ,IDISM


 WHERE
 G.IDPRJ=8
 --AND B.CODTMV LIKE '1.1.0%'
 --AND L.CODCMP='MR10823'
 --AND A.IDMOV=176493
 --AND C.PAGREC=2 --apagar


 --SELECT * FROM MISM WHERE IDPRJ=8

 --SELECT * FROM MCNTPDOMOV WHERE IDPRJ=8

 /*
 MPRJ - PROJETO
 MTAREFA - TAREFA
 MCMP - COMPOSIÇÃO
 MISM - INSUMO
 MISMPRC - PREÇO DO INSUMO
 MCNT - CONTRATO
 MCNTPDOMOV - VINCULO DO PERIODO COM TMOV

 */