SELECT  TITMMOV.CODCOLIGADA, TITMMOV.IDMOV, TITMMOV.NSEQITMMOV, TITMMOV.IDPRJ, TITMMOV.IDCNTOP, 
                                      TMOV.SEGUNDONUMERO, TMOV.NUMEROMOV, TMOV.CODTMV+'-'+TTMV.NOME AS DESCRICAOTIPOMOV, TPRODUTO.CODIGOPRD, 
                                       TPRODUTO.NOMEFANTASIA AS DESCRICAOPRD, 
CASE TTMVEXT.USADEDUCAOCNT
WHEN 1 THEN TITMMOV.VALORLIQUIDO
WHEN 2 THEN TITMMOV.VALORBRUTOITEM
WHEN 3 THEN TITMMOV.VALOROPFRM1
WHEN 4 THEN TITMMOV.VALOROPFRM2
WHEN 5 THEN TITMMOV.RATEIOCCUSTODEPTO
WHEN 6 THEN TITMMOV.VALORFINANCEIRO
END AS VALORITEM, TMOV.CODMOEVALORLIQUIDO
FROM TITMMOV, TMOV, TTMV, TPRODUTO, TTMVEXT--, MCNTPDODEDITMMOV
WHERE TMOV.CODCOLIGADA = TITMMOV.CODCOLIGADA
AND TMOV.IDMOV = TITMMOV.IDMOV
AND TMOV.CODCOLIGADA = TTMV.CODCOLIGADA
AND TTMV.CODTMV = TMOV.CODTMV
AND TITMMOV.IDPRD = TPRODUTO.IDPRD
AND TMOV.CODCOLIGADA = TTMVEXT.CODCOLIGADA
AND TMOV.CODTMV = TTMVEXT.CODTMV
AND TTMVEXT.USADEDUCAOCNT > 0
AND TTMV.GERAMOVPED = 0  AND (TTMV.CODTMV LIKE '1.2%' OR TTMV.CODTMV LIKE '2.2%' ) 
AND TITMMOV.CODCOLIGADA = 1
AND TITMMOV.IDPRJ = 248
AND TITMMOV.IDCNTOP = 28
AND TMOV.STATUS <> 'C'
ORDER BY TITMMOV.IDMOV, TITMMOV.NSEQITMMOV
