SELECT * FROM MOBJCNT WHERE IDPRJ=248 and IDCNT=28
SELECT * FROM MOBJCNTMED WHERE IDPRJ=248
SELECT * FROM MTAREFA WHERE IDPRJ=248
select * from MCNT WHERE IDPRJ=248

select * from MPDODETRET WHERE IDPRJ=248 and IDCNT=28 -- medição de produto vinculado valor e percentual
select * from MCNTPDODEDITMMOV WHERE IDPRJ=248 and IDCNT=28 --itens vinculados em medição
select * from MOBJCNTMED WHERE IDPRJ=248 and IDCNT=28
MOBJCNTMED

SELECT * FROM MPDOCOMPL where IDPRJ=248 and IDCNT=28

select * from GLINKSREL where MASTERTABLE='titmmov'

SELECT NSEQITMCNT, NSEQITMCNTDEST, NSEQITMCNTMEDICAO, * FROM TITMMOV WHERE IDMOV=176467
SELECT * FROM TITMM