--USE [CorporeRM]
--GO

--/****** Object:  StoredProcedure [dbo].[sp_addextendedproperty]    Script Date: 06/04/2018 16:20:41 ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO


--ALTER PROCEDURE [dbo].[sp_addextendedproperty] AS

--DELETE SFREQUENCIA WHERE  DATA=CONVERT(DATETIME, FLOOR(CONVERT(FLOAT(24), GETDATE())))

--INSERT INTO SFREQUENCIA 
--SELECT CODCOLIGADA, IDHORARIOTURMA, CODHOR, IDTURMADISC, CODFILIAL, CODPREDIO, CODSALA, DATAINICIAL, DATAFINAL, LOCACAO, TIPOAULA, CODBLOCO, CODTIPOSALA, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON, IDHORARIOTURMAVINC, CODSUBTURMA, SCIENTIAACTIVITYHOSTKEY
--FROM dbo.SHORARIOTURMA
--GO
/*
•	qual o texto que coloca quando o aluno sair mais cedo;
•	quando o aluno chegar atrasado;
•	quando não vir a escola;
•	quando perder aula;
•	se tem alguma diferente das demais citadas acima;
*/


SELECT 
SET4.COLIGADA,

SET4.IDOCORALUNO+1 'IDOCORALUNO',
SET4.NUMEROCARTEIRINHA ,
'11' CODOCORRENCIAGRUPO,
'144' CODCORRENCIATIPO,
SET4.IDPERLET,
SET4.ID_TURMADISCPLICA 'IDTURMADISC',
GETDATE() 'DATAOCORRENCIA',

CASE 

	WHEN SET4.ENTRADA_ACESSO IS NULL OR SET4.SAINDA_ACESSO IS NULL THEN '5 - ALUNO TEVE PROBLEMAS NA MARCAÇÃO DA CATRACA'
	WHEN SET4.ENTRADA_ACESSO > SET4.HORARIO_INICIAL_ALULA THEN '1 - O ALUNO CHEGOU ATRASADO NA AULA DE '+SET4.NOME_DISCIPLICA 
	WHEN SET4.SAINDA_ACESSO < SET4.HORARIO_FINAL_AULA THEN '2 - O ALUNO SAIU MAIS CEDO'
	--WHEN --SET4.HORARIO_FINAL_AULA < SET4.ENTRADA_ACESSO 
	WHEN (100.0 * DATEDIFF(MINUTE, SET4.HORARIO_INICIAL_ALULA, SET4.HORARIO_FINAL_AULA ) / DATEDIFF(MINUTE, SET4.ENTRADA_ACESSO, SET4.SAINDA_ACESSO) <= 70) THEN '3 - O ALUNO NÃO ASSISTIU  70% DE AULA PREVISTA'
	WHEN SET4.ENTRADA_ACESSO IS NULL AND SET4.SAINDA_ACESSO IS NULL THEN '4 - O ALUNO NÃO VEIO A ESCOLA HOJE'
	WHEN SET4.HORARIO_INICIAL_ALULA >= SET4.ENTRADA_ACESSO AND SET4.HORARIO_FINAL_AULA <= SET4.SAINDA_ACESSO THEN '6 - O ALUNO COMPARECEU A AULA'
ELSE
	'LOGICA INCORRENTA, FAVOR VERIFICAR!!!'
	
END AS 'OBSERVACOES',

SET4.HORARIO_INICIAL_ALULA,
SET4.HORARIO_FINAL_AULA,
SET4.ENTRADA_ACESSO,
SET4.SAINDA_ACESSO,

'1' DISPONIVELWEB,
'mestre' RECCREATEDBY,
SET4.DATA_AULODISCIPLICA RECCREATEDON,
'mestre' RECMODIFIEDBY,
SET4.DATA_AULODISCIPLICA RECMODIFIEDON,
'N' RESPONSAVELCIENTE

FROM
(SELECT 

SET2.CODCOLIGADA AS COLIGADA,
SET2.IDHORARIOTURMA AS ID_HORARIO,
SET2.IDTURMADISC AS ID_TURMADISCPLICA,
SET2.RA AS RA_ALUNO,
SET2.DATA as DATA_AULODISCIPLICA,
SET1.DATA_CONVERTIDA AS DATA_ACESSOCATRACA,
SET1.NUMEROCARTEIR,
SET2.NUMEROCARTEIRINHA  AS NUMEROCARTEIRINHA ,
SET2.NOME_DISCIPLICA,
SET2.HORARIO_INICIAL_ALULA,
SET2.HORARIO_FINAL_AULA,
SET2.IDPERLET,
SET3.IDOCORALUNO,
MAX( 
 CASE 
     WHEN SET1.tipo_acesso = '1'   THEN HORAS_CONVERTIDA
	
	 END) AS ENTRADA_ACESSO,

MAX( 
 CASE 
     WHEN SET1.tipo_acesso = '2' THEN HORAS_CONVERTIDA
	
	 END) AS SAINDA_ACESSO
FROM 
(SELECT DISTINCT

E1.ID_PESSOAS,
E1.DATA_CONVERTIDA,
E1.HORAS_CONVERTIDA,
E1.MATRICULA,
E1.NUMEROCARTEIR,
E1.NOME_PESSOA,
E1.equipamento_id,
E1.TIPO_ACESSO,
E1.DESCRICAO,
E1.negado,
E1.DATA_EVA

         FROM ( 
SELECT DISTINCT
PPC.ID AS ID_PESSOAS,
EVA.pessoa_id AS ID_EVENTOSACESSOS,
CONVERT (DATETIME, EVA.DATA, 126)AS DATA_CONVERTIDA,
DBO.CONVERTESEGUNDOSEMHORAS(EVA.HORA) AS HORAS_CONVERTIDA,
EVA.DATA AS DATA_DE_ACESSO,
EVA.hora,
EVA.equipamento_id,
EVA.tipo_acesso,
EVA.descricao,
EVA.negado,
PPC.n_identificador AS MATRICULA,
PPC.NOME AS NOME_PESSOA,
SMA.NUMCARTEIRA AS NUMEROCARTEIR,
SMA.CODTURMA,
EVA.DATA AS DATA_EVA


FROM [192.168.6.12].[SecullumAcessoNet].[DBO].PESSOAS  PPC (NOLOCK ) 

LEFT JOIN [192.168.6.12].[SecullumAcessoNet].[DBO].eventos_acessos EVA (NOLOCK) ON  PPC.id = EVA.pessoa_id 

LEFT JOIN SMATRICPL SMA (NOLOCK) ON  SMA.NUMCARTEIRA COLLATE SQL_Latin1_General_CP1_CI_AI = PPC.n_identificador COLLATE SQL_Latin1_General_CP1_CI_AI

WHERE CONVERT (DATETIME, EVA.DATA) = '2018-04-06'
--DATA=CONVERT(DATETIME, FLOOR(CONVERT(FLOAT(24), GETDATE())))

) E1

) AS SET1 INNER JOIN 

(SELECT  
SMA.NUMCARTEIRA AS NUMEROCARTEIRINHA,
SRT.IDTURMADISC AS CODIGO_DISPLICA,
SDI.NOME AS NOME_DISCIPLICA,
SHH.HORAINICIAL AS HORARIO_INICIAL_ALULA,
SHH.HORAFINAL AS HORARIO_FINAL_AULA,
SPP.DATA,
SMA.CODCOLIGADA,
SHO.IDHORARIOTURMA,
SPP.IDTURMADISC,
SMA.RA,
SPL.IDPERLET 'IDPERLET'


 FROM SMATRICPL SMA (NOLOCK) 
 
 INNER JOIN STURMA STU (NOLOCK ) ON       SMA.CODCOLIGADA = STU.CODCOLIGADA
                         AND              SMA.CODFILIAL   = STU.CODFILIAL
						 AND              SMA.CODTURMA    = STU.CODTURMA
				         AND              SMA.IDPERLET    = STU.IDPERLET

INNER JOIN STURMADISC SRT (NOLOCK) ON     STU.CODCOLIGADA = SRT.CODCOLIGADA
						 AND              STU.CODFILIAL   = SRT.CODFILIAL
						 AND			  STU.CODTURMA    = SRT.CODTURMA
						 AND              STU.IDPERLET    = SRT.IDPERLET

INNER JOIN SDISCIPLINA SDI (NOLOCK) ON    SRT.CODCOLIGADA  = SDI.CODCOLIGADA
                         AND              SRT.CODDISC      = SDI.CODDISC
 
INNER JOIN SHABILITACAOFILIAL SHA (NOLOCK) ON SMA.CODCOLIGADA = SHA.CODCOLIGADA
                         AND                SMA.IDHABILITACAOFILIAL = SHA.IDHABILITACAOFILIAL

INNER JOIN SHORARIOTURMA SHO (NOLOCK ) ON SRT.CODCOLIGADA = SHO.CODCOLIGADA 
                             AND          SRT.IDTURMADISC = SHO.IDTURMADISC

INNER JOIN SHORARIO SHH ( NOLOCK ) ON SHO.CODCOLIGADA = SHH.CODCOLIGADA
                              AND     SHO.CODHOR      = SHH.CODHOR

INNER JOIN SPLETIVO SPL (NOLOCK) ON SMA.CODCOLIGADA = SPL.CODCOLIGADA 
                              AND   SMA.CODFILIAL   = SPL.CODFILIAL
							  AND   SMA.IDPERLET    = SPL.IDPERLET

LEFT JOIN SPLANOAULA SPP (NOLOCK) ON SHO.CODCOLIGADA = SPP.CODCOLIGADA
                              AND     SHO.IDHORARIOTURMA = SPP.IDHORARIOTURMA
							  AND     SHO.CODHOR         = SPP.CODHOR
							  AND     SHO.IDTURMADISC    =SPP.IDTURMADISC


							  WHERE 
							  SPL.CODPERLET >= '2018' 
							  AND SDI.CODCOLIGADA = '1'
							  AND SHA.CODFILIAL = '1'
							  AND SPP.DATA = '2018-04-06'

							  
) SET2 ON SET1.NUMEROCARTEIR = SET2.NUMEROCARTEIRINHA
  --INNER JOIN
  FULL OUTER JOIN
(
SELECT 
	A.CODCOLIGADA,
	A.RA 'NUMEROCARTEIRINHA',
	A.IDTURMADISC 'IDTURMADISC',
	MAX(B.IDOCORALUNO) 'IDOCORALUNO'
FROM SFREQUENCIA A
	INNER JOIN SOCORRENCIAALUNO B ON 
		A.CODCOLIGADA = B.CODCOLIGADA AND 
		A.IDTURMADISC = B.IDTURMADISC AND 
		A.RA = B.RA AND A.DATA = B.DATAOCORRENCIA
WHERE
	B.CODCOLIGADA = 1
GROUP BY 
	A.CODCOLIGADA,
	A.RA,
	A.IDTURMADISC
) 
SET3 ON 
	SET3.NUMEROCARTEIRINHA = SET1.NUMEROCARTEIR AND 
	SET2.CODIGO_DISPLICA = SET3.IDTURMADISC AND 
	SET2.CODCOLIGADA = SET3.CODCOLIGADA

WHERE 
     SET1.DATA_CONVERTIDA = SET2.DATA	

GROUP BY 

SET2.CODCOLIGADA,
SET2.RA,
SET1.NUMEROCARTEIR,
SET2.IDHORARIOTURMA,
SET2.IDTURMADISC,
SET2.DATA,
SET1.DATA_CONVERTIDA,
SET2.NOME_DISCIPLICA,
SET2.HORARIO_INICIAL_ALULA,
SET2.HORARIO_FINAL_AULA,
SET2.NUMEROCARTEIRINHA,
SET2.IDPERLET,
SET3.IDOCORALUNO
) SET4
--WHERE
--	SET4.SAINDA_ACESSO IS NULL

GROUP BY 
SET4.COLIGADA,
SET4.NUMEROCARTEIRINHA ,
SET4.IDPERLET,
SET4.ID_TURMADISCPLICA,
SET4.ENTRADA_ACESSO,
SET4.SAINDA_ACESSO,
SET4.HORARIO_INICIAL_ALULA,
SET4.HORARIO_FINAL_AULA,
SET4.DATA_AULODISCIPLICA,
SET4.NOME_DISCIPLICA,
SET4.IDOCORALUNO,

SET4.HORARIO_INICIAL_ALULA,
SET4.HORARIO_FINAL_AULA,
SET4.ENTRADA_ACESSO,
SET4.SAINDA_ACESSO





ORDER BY --SET4.ENTRADA_ACESSO, SET4.SAINDA_ACESSO, 
OBSERVACOES ASC

--GO


--SELECT MAX(IDCORALUNO) SELECT * FROM SOCORRENCIAALUNO WHERE CODCOLIGADA=1