--IF NOT EXISTS(SELECT RA FROM SOCORRENCIAALUNO WHERE DATAOCORRENCIA = GETDATE())
--INSERT INTO dbo.SOCORRENCIAALUNO (CODCOLIGADA, IDOCORALUNO, RA, CODOCORRENCIAGRUPO, CODOCORRENCIATIPO, IDPERLET, IDTURMADISC, DATAOCORRENCIA, OBSERVACOES, DISPONIVELWEB, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON, RESPONSAVELCIENTE)
SELECT 
SET4.COLIGADA 'CODCOLIGADA',
(SELECT 
		MAX(IDOCORALUNO) 
			FROM SOCORRENCIAALUNO 
			WHERE CODCOLIGADA=1)+(ROW_NUMBER() OVER 
			(ORDER BY IDOCORALUNO)) AS IDOCORALUNO,
SET4.RA,
'11' CODOCORRENCIAGRUPO,
'144' CODOCORRENCIATIPO,
SET4.IDPERLET,
SET4.ID_TURMADISCPLICA 'IDTURMADISC',
GETDATE() 'DATAOCORRENCIA',
--DATEDIFF(MINUTE, SET4.HORARIO_INICIAL_AULA, SET4.HORARIO_FINAL_AULA) 'HORARIO',
--DATEDIFF(MINUTE, SET4.ENTRADA_ACESSO, SET4.SAIDA_ACESSO) 'CATRACA',
--SET4.ENTRADA, SET4.SAIDA,
(
CASE 
------------------------------------------------------------ ALUNO FALTOU AO COLEGIO----------------------------------------------------------------------
WHEN SET4.ENTRADA_ACESSO IS NULL AND SET4.SAIDA_ACESSO IS NULL THEN '1 - O ALUNO FALTOU AO COLEGIO '                    ----- 1  ( STATUS ALUNO FALTO ) 
----------------------------------------------------------------------------------------------------------------------------------------------------------

-----------------------------------------------------------ALUNO TEVE PROBLEMAS NA MARCAÇÃO DA CATRACA ---------------------------------------------------
 WHEN SET4.ENTRADA_ACESSO IS NULL OR SET4.SAIDA_ACESSO IS NULL THEN '2 - ALUNO TEVE PROBLEMAS NA MARCAÇÃO DA CATRACA' -- ( STATUS MARCAÇÃO INCORRETA )
----------------------------------------------------------------------------------------------------------------------------------------------------------

-----------------------------------------------------------ALUNO CHEGOU ATRASA NA PRIMEIRA AULA POREM ENTRO NA SEGUNDA--------------------------------------
	WHEN DATEADD(MINUTE,-5, SET4.ENTRADA_ACESSO) > SET4.HORARIO_INICIAL_AULA AND SET4.ENTRADA_ACESSO < SET4.HORARIO_FINAL_AULA AND SET4.AULA IN ( 01,02)
	THEN '3 - O ALUNO CHEGOU ATRASADO'                                     -- ( VISÃO POR DISCIPLICA )    ( STATUS ALUNO CHEGOU ATRASADO NA PRIMEIRA AULA)
------------------------------------------------------------------------------------------------------------------------------------------------------------

---------------------------------------------------------------------- ALUNO RECEBEU FALTO POR CHEGAR DEPOIS DO SEGUNDO HORARIO-----------------------------
      WHEN DATEADD(MINUTE,-5, SET4.ENTRADA_ACESSO) > SET4.HORARIO_INICIAL_AULA AND SET4.ENTRADA_ACESSO < SET4.HORARIO_FINAL_AULA AND SET4.AULA=02
   THEN '4 - O ALUNO RECEBEU FALTO POR CHEGAR APOS SEGUNDA AULA ' -- ( VISÃO SEGUNDO HORARIO )  ( STATUS ALUNO RECEBEU FALTA POR CHEGAR APOS SEGUNDA AULA)
------------------------------------------------------------------------------------------------------------------------------------------------------------

-----------------------------------------------------------------PORCENTAGEM DE 70 AULA POR DISCIPLICA NÃO ASSISTIU 70 % ( SAIU MAIS SEDO)-------------------
	WHEN (100.0 * DATEDIFF(MINUTE, SET4.ENTRADA, SET4.SAIDA ) / DATEDIFF(MINUTE, SET4.HORARIO_INICIAL_AULA, SET4.HORARIO_FINAL_AULA) <= 70) 
		AND SET4.ENTRADA <= SET4.HORARIO_FINAL_AULA and SET4.SAIDA >= SET4.HORARIO_INICIAL_AULA  
		THEN '5 - ALUNO SAIU ANTES DO FIM DA AULA '
------------------------------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------ALUNO NÃO ASSISTIU A AULA FALTA A AULA --------------------------------------------------------------
	WHEN SET4.ENTRADA_ACESSO > SET4.HORARIO_INICIAL_AULA AND SET4.ENTRADA_ACESSO > SET4.HORARIO_FINAL_AULA OR SET4.SAIDA_ACESSO < SET4.HORARIO_INICIAL_AULA
		THEN '6 - ALUNO FALTA A AULA '  -- ( STATUS ALUNO NÃO ASSISTIU A AULO VISÃO POR DISCIPLICA ) 
------------------------------------------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------ALUNO ENTROU NO COLEGIO-------------------------------------------------------------------------------
WHEN SET4.HORARIO_INICIAL_AULA > SET4.ENTRADA_ACESSO AND SET4.HORARIO_FINAL_AULA < SET4.SAIDA_ACESSO THEN '7 - O ALUNO COMPARECEU A AULA' -- ( STAUTS COMPARECEU A AULA POR DISCIPLICA)
------------------------------------------------------------------------------------------------------------------------------------------------------------

-----------------------------------------------------------------NOTIFICAÇÃO POR AULA ASSISTIDA ( DESATIVADA )----------------------------------------------
	--WHEN DATEADD(MINUTE,-3, SET4.ENTRADA_ACESSO) < SET4.HORARIO_INICIAL_AULA AND DATEADD(MINUTE,3, SET4.SAIDA_ACESSO) > SET4.HORARIO_FINAL_AULA 
	--	THEN '7 - O ALUNO COMPARECEU A AULA QUE SE INICIA AS '+SET4.HORARIO_INICIAL_AULA+ ' E FINALIZA AS '+SET4.HORARIO_FINAL_AULA+' DA DISCIPLINA DE '+UPPER(SET4.NOME_DISCIPLICA)
-----------------------------------------------------------------------------------------------------------------------------------------------------------

-----------------------------------------------------------------ALUNO CHEGOU APÓS O INICIO DAS AULAS MAS TEVE 70%-----------------------------------------
	WHEN (100.0 * DATEDIFF(MINUTE, SET4.ENTRADA, DATEADD(MINUTE,3, SET4.SAIDA) ) / DATEDIFF(MINUTE, SET4.HORARIO_INICIAL_AULA, SET4.HORARIO_FINAL_AULA) >= 70) 
		AND SET4.ENTRADA_ACESSO > SET4.HORARIO_INICIAL_AULA 
		THEN ' 8 - O ALUNO CHEGOU ATRASADO' -- ( STATUS ALUNO RECEBEU CHEGOU ATRASA MAIS TEVE PRESENÇA ) 
------------------------------------------------------------------------------------------------------------------------------------------------------------

---------------------------------------------------------------------Aulas Encerradas / Saiu da Escola -----------------------------------------------------
 	WHEN DATEADD(MINUTE,-5, SET4.ENTRADA_ACESSO) > SET4.HORARIO_INICIAL_AULA AND SET4.ENTRADA_ACESSO < SET4.HORARIO_FINAL_AULA AND  SET4.AULA = MAX(SET4.AULA) 
	THEN '9 - AULAS ENCERRADAS / SAIU DO COLEGIO'                                 -- ( VISÃO POR DISCIPLICA )    ( STATUS ALUNO CHEGOU ATRASADO NA PRIMEIRA AULA) 
------------------------------------------------------------------------------------------------------------------------------------------------------------
ELSE
	'10 - LOGICA INCORRENTA, FAVOR VERIFICAR!!!'
END) AS OBSERVACOES,

--SET4.HORARIO_INICIAL_AULA,
--SET4.HORARIO_FINAL_AULA,
--DATEADD(MINUTE,-3, SET4.ENTRADA_ACESSO) 'TOLERANCIA_ENTRADA',
--DATEADD(MINUTE,3, SET4.SAIDA_ACESSO) 'TOLERANCIA_SAIDA',
--SET4.ENTRADA_ACESSO,
--SET4.SAIDA_ACESSO,
SET4.DATA_ACESSOCATRACA,
'1' DISPONIVELWEB,
'mestre' RECCREATEDBY,
GETDATE() RECCREATEDON,
'mestre' RECMODIFIEDBY,
GETDATE() RECMODIFIEDON,
'N' RESPONSAVELCIENTE
FROM
(
SELECT
		case when SET31.ENTRADA_ACESSO > SET31.HORARIO_INICIAL_AULA then SET31.ENTRADA_ACESSO else SET31.HORARIO_INICIAL_AULA end as ENTRADA,
        case when SET31.SAIDA_ACESSO < SET31.HORARIO_FINAL_AULA then SET31.SAIDA_ACESSO else SET31.HORARIO_FINAL_AULA end as SAIDA,
SET31.COLIGADA,
SET31.ID_HORARIO,
SET31.ID_TURMADISCPLICA,
SET31.RA_ALUNO,
SET31.DATA_AULODISCIPLICA,
SET31.DATA_ACESSOCATRACA,
SET31.NUMEROCARTEIR,
SET31.NUMEROCARTEIRINHA ,
SET31.NOME_DISCIPLICA,
SET31.HORARIO_INICIAL_AULA,
SET31.HORARIO_FINAL_AULA,
SET31.IDPERLET,
SET31.IDOCORALUNO,
SET31.ENTRADA_ACESSO,
SET31.SAIDA_ACESSO,
SET31.AULA,
SET31.RA

FROM
(SELECT 

SET2.CODCOLIGADA AS COLIGADA,
SET2.IDHORARIOTURMA AS ID_HORARIO,
SET2.IDTURMADISC AS ID_TURMADISCPLICA,
SET2.RA AS RA_ALUNO,
SET2.DATA as DATA_AULODISCIPLICA,
SET1.DATA_CONVERTIDA AS DATA_ACESSOCATRACA,
SET1.NUMEROCARTEIR,
SET2.NUMEROCARTEIRINHA  AS NUMEROCARTEIRINHA ,
SET2.NOME_DISCIPLICA,
SET2.HORARIO_INICIAL_AULA,
SET2.HORARIO_FINAL_AULA,
SET2.IDPERLET,
SET3.IDOCORALUNO,
SET2.AULA,
SET2.RA,
MAX( 
 CASE 
     WHEN SET1.tipo_acesso = '1'   THEN HORAS_CONVERTIDA
	
	 END) AS ENTRADA_ACESSO,

MAX( 
 CASE 
     WHEN SET1.tipo_acesso = '2' THEN HORAS_CONVERTIDA
	
	 END) AS SAIDA_ACESSO
FROM 
(
SELECT  
SMA.NUMCARTEIRA AS NUMEROCARTEIRINHA,
SRT.IDTURMADISC AS CODIGO_DISPLICA,
SDI.NOME AS NOME_DISCIPLICA,
SHH.HORAINICIAL AS HORARIO_INICIAL_AULA,
SHH.HORAFINAL AS HORARIO_FINAL_AULA,
SPP.DATA,
SMA.CODCOLIGADA,
SHO.IDHORARIOTURMA,
SPP.IDTURMADISC,
SMA.RA,
SPL.IDPERLET 'IDPERLET',
SHH.AULA


 FROM SMATRICPL SMA (NOLOCK) 
 
 INNER JOIN STURMA STU (NOLOCK ) ON       SMA.CODCOLIGADA = STU.CODCOLIGADA
                         AND              SMA.CODFILIAL   = STU.CODFILIAL
						 AND              SMA.CODTURMA    = STU.CODTURMA
				         AND              SMA.IDPERLET    = STU.IDPERLET

INNER JOIN STURMADISC SRT (NOLOCK) ON     STU.CODCOLIGADA = SRT.CODCOLIGADA
						 AND              STU.CODFILIAL   = SRT.CODFILIAL
						 AND			  STU.CODTURMA    = SRT.CODTURMA
						 AND              STU.IDPERLET    = SRT.IDPERLET

INNER JOIN SDISCIPLINA SDI (NOLOCK) ON    SRT.CODCOLIGADA  = SDI.CODCOLIGADA
                         AND              SRT.CODDISC      = SDI.CODDISC
 
INNER JOIN SHABILITACAOFILIAL SHA (NOLOCK) ON SMA.CODCOLIGADA = SHA.CODCOLIGADA
                         AND                SMA.IDHABILITACAOFILIAL = SHA.IDHABILITACAOFILIAL

INNER JOIN SHORARIOTURMA SHO (NOLOCK ) ON SRT.CODCOLIGADA = SHO.CODCOLIGADA 
                             AND          SRT.IDTURMADISC = SHO.IDTURMADISC

INNER JOIN SHORARIO SHH ( NOLOCK ) ON SHO.CODCOLIGADA = SHH.CODCOLIGADA
                              AND     SHO.CODHOR      = SHH.CODHOR

INNER JOIN SPLETIVO SPL (NOLOCK) ON SMA.CODCOLIGADA = SPL.CODCOLIGADA 
                              AND   SMA.CODFILIAL   = SPL.CODFILIAL
							  AND   SMA.IDPERLET    = SPL.IDPERLET

LEFT JOIN SPLANOAULA SPP (NOLOCK) ON SHO.CODCOLIGADA = SPP.CODCOLIGADA
                              AND     SHO.IDHORARIOTURMA = SPP.IDHORARIOTURMA
							  AND     SHO.CODHOR         = SPP.CODHOR
							  AND     SHO.IDTURMADISC    =SPP.IDTURMADISC


							  WHERE 
							  SPL.CODPERLET >= '2018' 
							  AND SDI.CODCOLIGADA = '1'
							  AND SHA.CODFILIAL = '1'
							 -- AND SPP.DATA = '2018-04-05'
							 -- AND SMA.CODTURMA = 'EM01A101'
							 -- AND SRT.IDTURMADISC = '7195'
							 AND SMA.RA = '15508035'


							  --AND SRT.CODTURMA = 'EM03C101'
							  --
							  --AND SMA.RA='15509010'
							AND SPP.DATA BETWEEN '2018-04-04' AND '2018-04-09'

) AS SET2 LEFT JOIN 

(SELECT DISTINCT

E1.ID_PESSOAS,
E1.DATA_CONVERTIDA,
E1.HORAS_CONVERTIDA,
E1.MATRICULA,
E1.NUMEROCARTEIR,
E1.NOME_PESSOA,
E1.equipamento_id,
E1.TIPO_ACESSO,
E1.DESCRICAO,
E1.negado,
E1.DATA_EVA

         FROM ( 
SELECT DISTINCT
PPC.ID AS ID_PESSOAS,
EVA.pessoa_id AS ID_EVENTOSACESSOS,
CONVERT (DATETIME, EVA.DATA, 126)AS DATA_CONVERTIDA,
DBO.CONVERTESEGUNDOSEMHORAS(EVA.HORA) AS HORAS_CONVERTIDA,
EVA.DATA AS DATA_DE_ACESSO,
EVA.hora,
EVA.equipamento_id,
EVA.tipo_acesso,
EVA.descricao,
EVA.negado,
PPC.n_identificador AS MATRICULA,
PPC.NOME AS NOME_PESSOA,
SMA.NUMCARTEIRA AS NUMEROCARTEIR,
SMA.CODTURMA,
EVA.DATA AS DATA_EVA


FROM [192.168.6.12].[SecullumAcessoNet].[DBO].PESSOAS  PPC (NOLOCK ) 

LEFT JOIN [192.168.6.12].[SecullumAcessoNet].[DBO].eventos_acessos EVA (NOLOCK) ON  PPC.id = EVA.pessoa_id 

LEFT JOIN SMATRICPL SMA (NOLOCK) ON  SMA.NUMCARTEIRA COLLATE SQL_Latin1_General_CP1_CI_AI = PPC.n_identificador COLLATE SQL_Latin1_General_CP1_CI_AI

--WHERE CONVERT (DATETIME, EVA.DATA) = '2018-04-05'
WHERE CONVERT (DATETIME, EVA.DATA) BETWEEN '2018-04-04' AND '2018-04-09'
--DATA=CONVERT(DATETIME, FLOOR(CONVERT(FLOAT(24), GETDATE())))

) E1					  
) SET1 ON SET1.NUMEROCARTEIR = SET2.NUMEROCARTEIRINHA
  LEFT JOIN
(
SELECT 
	A.CODCOLIGADA,
	A.RA 'NUMEROCARTEIRINHA',
	A.IDTURMADISC 'IDTURMADISC',
	B.IDOCORALUNO 'IDOCORALUNO'
FROM SFREQUENCIA A
	INNER JOIN SOCORRENCIAALUNO B ON 
		A.CODCOLIGADA = B.CODCOLIGADA AND 
		A.IDTURMADISC = B.IDTURMADISC AND 
		A.RA = B.RA AND A.DATA = B.DATAOCORRENCIA
WHERE
	B.CODCOLIGADA = 1
GROUP BY 
	A.CODCOLIGADA,
	A.RA,
	A.IDTURMADISC,
	B.IDOCORALUNO
) 
SET3 ON 
	SET3.NUMEROCARTEIRINHA = SET1.NUMEROCARTEIR AND 
	SET2.CODIGO_DISPLICA = SET3.IDTURMADISC AND 
	SET2.CODCOLIGADA = SET3.CODCOLIGADA

--WHERE 
--     SET1.DATA_CONVERTIDA = SET2.DATA	

GROUP BY 

SET2.CODCOLIGADA,
SET2.RA,
SET1.NUMEROCARTEIR,
SET2.IDHORARIOTURMA,
SET2.IDTURMADISC,
SET2.DATA,
SET1.DATA_CONVERTIDA,
SET2.NOME_DISCIPLICA,
SET2.HORARIO_INICIAL_AULA,
SET2.HORARIO_FINAL_AULA,
SET2.NUMEROCARTEIRINHA,
SET2.IDPERLET,
SET3.IDOCORALUNO,
SET2.AULA,
SET2.RA
) SET31
--WHERE

--	SET31.ENTRADA <= SET31.HORARIO_FINAL_AULA and
--    SET31.SAIDA >= SET31.HORARIO_INICIAL_AULA
) SET4

GROUP BY 
SET4.COLIGADA,
SET4.NUMEROCARTEIRINHA ,
SET4.IDPERLET,
SET4.ID_TURMADISCPLICA,
SET4.ENTRADA_ACESSO,
SET4.SAIDA_ACESSO,
SET4.HORARIO_INICIAL_AULA,
SET4.HORARIO_FINAL_AULA,
SET4.DATA_AULODISCIPLICA,
SET4.NOME_DISCIPLICA,
SET4.IDOCORALUNO,
SET4.DATA_ACESSOCATRACA,
SET4.HORARIO_INICIAL_AULA,
SET4.HORARIO_FINAL_AULA,
SET4.ENTRADA_ACESSO,
SET4.SAIDA_ACESSO,
SET4.ENTRADA, SET4.SAIDA,
SET4.AULA,
SET4.RA

ORDER BY SET4.ENTRADA_ACESSO, SET4.SAIDA_ACESSO
