SP_HELP TPRODUTODEF

ALTER TABLE dbo.TPRODUTODEF ALTER COLUMN CODTB3FAT VARCHAR(10) NULL ;

--ALTER TABLE Pessoas ALTER COLUMN NomeRazaoSocial [VARCHAR](250) NULL;

--CREATE TABLE [Pessoas] (
--    [IdPessoa] INT,
--    [NomeRazaoSocial] [VARCHAR](250) NOT NULL);
--GO