SELECT
TABELAS.NAME, COLUNAS.NAME AS COLUNA,TIPOS.NAME AS TIPO,
COLUNAS.LENGTH AS TAMANHO,COLUNAS.ISNULLABLE AS EH_NULO

FROM
sysobjects AS TABELAS,syscolumns AS COLUNAS,systypes AS TIPOS

WHERE
TABELAS.ID = COLUNAS.ID AND COLUNAS.USERTYPE = TIPOS.USERTYPE
AND TABELAS.NAME = 'pfunc'
AND COLUNAS.isnullable = 0
