/**********ALTERAÇÃO DA TABELA CIE'CODFILIAL'0 EX.:C1E990 DA BASE DE DADOS TAF COD=4 O STATUS FICA TRANSMITIDO************/
SELECT C1E_STATUS,*  FROM C1E990

--update C1E990 set C1E_STATUS = '0' where c1e_id = '000001'

/**********ALTERAÇÃO DA TABELA SPED400b DA BASE DE DADOS TSS COD=4 O STATUS FICA TRANSMITIDO************/
 select * from SPED400b
