USE [CorporeRM]
GO

/****** Object:  StoredProcedure [dbo].[ATUALIZA_CATRACA]    Script Date: 01/08/2018 00:21:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE procedure [dbo].[ATUALIZA_CATRACA1] AS

DELETE FROM ZALTERACAO_CATRACA WHERE DT_ATUALIZA < GETDATE() -1

/*TIRADENTES */
UPDATE [192.168.4.12].[SecullumAcessoNet].[DBO].PESSOAS SET N_IDENTIFICADOR = Z.NUMCARTEIRA
FROM ZALTERACAO_CATRACA z (NOLOCK)
	inner JOIN [192.168.4.12].[SecullumAcessoNet].[DBO].PESSOAS P (NOLOCK)
	ON P.NOME COLLATE SQL_Latin1_General_CP1_CI_AI = z.NOME COLLATE SQL_Latin1_General_CP1_CI_AI
	INNER JOIN SMATRICPL SMA (NOLOCK) ON  SMA.ra COLLATE SQL_Latin1_General_CP1_CI_AI = z.ra COLLATE SQL_Latin1_General_CP1_CI_AI
WHERE 
	p.N_IDENTIFICADOR  COLLATE SQL_Latin1_General_CP1_CI_AI <> z.NUMCARTEIRA  COLLATE SQL_Latin1_General_CP1_CI_AI
	AND z.NUMCARTEIRA IS NOT NULL
	and sma.codstatus=2

/*RIBEIRÃO*/
UPDATE [192.168.1.10].[SecullumAcessoNet].[DBO].PESSOAS SET N_IDENTIFICADOR = Z.NUMCARTEIRA
FROM ZALTERACAO_CATRACA z (NOLOCK)
	inner JOIN [192.168.1.10].[SecullumAcessoNet].[DBO].PESSOAS P (NOLOCK)
	ON P.NOME COLLATE SQL_Latin1_General_CP1_CI_AI = z.NOME COLLATE SQL_Latin1_General_CP1_CI_AI
	INNER JOIN SMATRICPL SMA (NOLOCK) ON  SMA.ra COLLATE SQL_Latin1_General_CP1_CI_AI = z.ra COLLATE SQL_Latin1_General_CP1_CI_AI
WHERE 
	p.N_IDENTIFICADOR  COLLATE SQL_Latin1_General_CP1_CI_AI <> z.NUMCARTEIRA  COLLATE SQL_Latin1_General_CP1_CI_AI
	AND z.NUMCARTEIRA IS NOT NULL
	and sma.codstatus=2

/*RONDON*/
UPDATE [192.168.6.12].[SecullumAcessoNet].[DBO].PESSOAS SET N_IDENTIFICADOR = Z.NUMCARTEIRA
FROM ZALTERACAO_CATRACA z (NOLOCK)
	inner JOIN [192.168.6.12].[SecullumAcessoNet].[DBO].PESSOAS P (NOLOCK)
	ON P.NOME COLLATE SQL_Latin1_General_CP1_CI_AI = z.NOME COLLATE SQL_Latin1_General_CP1_CI_AI
	INNER JOIN SMATRICPL SMA (NOLOCK) ON  SMA.ra COLLATE SQL_Latin1_General_CP1_CI_AI = z.ra COLLATE SQL_Latin1_General_CP1_CI_AI
WHERE 
	p.N_IDENTIFICADOR  COLLATE SQL_Latin1_General_CP1_CI_AI <> z.NUMCARTEIRA  COLLATE SQL_Latin1_General_CP1_CI_AI
	AND z.NUMCARTEIRA IS NOT NULL
	and sma.codstatus=2

/*UBERABA*/
UPDATE [192.168.3.12].[SecullumAcessoNet].[DBO].PESSOAS SET N_IDENTIFICADOR = Z.NUMCARTEIRA
FROM ZALTERACAO_CATRACA z (NOLOCK)
	inner JOIN [192.168.3.12].[SecullumAcessoNet].[DBO].PESSOAS P (NOLOCK)
	ON P.NOME COLLATE SQL_Latin1_General_CP1_CI_AI = z.NOME COLLATE SQL_Latin1_General_CP1_CI_AI
	INNER JOIN SMATRICPL SMA (NOLOCK) ON  SMA.ra COLLATE SQL_Latin1_General_CP1_CI_AI = z.ra COLLATE SQL_Latin1_General_CP1_CI_AI
WHERE 
	p.N_IDENTIFICADOR  COLLATE SQL_Latin1_General_CP1_CI_AI <> z.NUMCARTEIRA  COLLATE SQL_Latin1_General_CP1_CI_AI
	AND z.NUMCARTEIRA IS NOT NULL
	and sma.codstatus=2

/*ISABEL*/
UPDATE [192.168.2.12].[SecullumAcessoNet].[DBO].PESSOAS SET N_IDENTIFICADOR = Z.NUMCARTEIRA
FROM ZALTERACAO_CATRACA z (NOLOCK)
	inner JOIN [192.168.2.12].[SecullumAcessoNet].[DBO].PESSOAS P (NOLOCK)
	ON P.NOME COLLATE SQL_Latin1_General_CP1_CI_AI = z.NOME COLLATE SQL_Latin1_General_CP1_CI_AI
	INNER JOIN SMATRICPL SMA (NOLOCK) ON  SMA.ra COLLATE SQL_Latin1_General_CP1_CI_AI = z.ra COLLATE SQL_Latin1_General_CP1_CI_AI
WHERE 
	p.N_IDENTIFICADOR  COLLATE SQL_Latin1_General_CP1_CI_AI <> z.NUMCARTEIRA  COLLATE SQL_Latin1_General_CP1_CI_AI
	AND z.NUMCARTEIRA IS NOT NULL
	and sma.codstatus=2




--DELETE FROM ZALTERACAO_CATRACA WHERE DT_ATUALIZA < GETDATE() -1

----/*TIRADENTES */
----UPDATE [192.168.4.12].[SecullumAcessoNet].[DBO].PESSOAS SET N_IDENTIFICADOR = NUMCARTEIRA
----FROM ZALTERACAO_CATRACA (NOLOCK)
----INNER JOIN [192.168.4.12].[SecullumAcessoNet].[DBO].PESSOAS P (NOLOCK)
----ON P.NOME COLLATE SQL_Latin1_General_CP1_CI_AI = ZALTERACAO_CATRACA.NOME COLLATE SQL_Latin1_General_CP1_CI_AI
----WHERE convert(CHAR,dt_atualiza,103) = convert(CHAR,getdate(),103) 
----AND N_IDENTIFICADOR  COLLATE SQL_Latin1_General_CP1_CI_AI <> NUMCARTEIRA  COLLATE SQL_Latin1_General_CP1_CI_AI
----AND NUMCARTEIRA IS NOT NULL

--/*RIBEIRÃO*/
--UPDATE [192.168.1.10].[SecullumAcessoNet].[DBO].PESSOAS SET N_IDENTIFICADOR = NUMCARTEIRA
--FROM ZALTERACAO_CATRACA (NOLOCK)
--INNER JOIN [192.168.1.10].[SecullumAcessoNet].[DBO].PESSOAS P (NOLOCK)
--ON P.NOME COLLATE SQL_Latin1_General_CP1_CI_AI = ZALTERACAO_CATRACA.NOME COLLATE SQL_Latin1_General_CP1_CI_AI
--WHERE convert(CHAR,dt_atualiza,103) = convert(CHAR,getdate(),103) 
--AND N_IDENTIFICADOR  COLLATE SQL_Latin1_General_CP1_CI_AI <> NUMCARTEIRA  COLLATE SQL_Latin1_General_CP1_CI_AI
--AND NUMCARTEIRA IS NOT NULL

--/*RONDON*/
--UPDATE [192.168.6.12].[SECULLUMACESSONET].[DBO].PESSOAS SET N_IDENTIFICADOR = NUMCARTEIRA
--FROM ZALTERACAO_CATRACA (NOLOCK)
--INNER JOIN [192.168.6.12].[SECULLUMACESSONET].[DBO].PESSOAS P (NOLOCK)
--ON P.NOME COLLATE SQL_Latin1_General_CP1_CI_AI = ZALTERACAO_CATRACA.NOME COLLATE SQL_Latin1_General_CP1_CI_AI
--WHERE convert(CHAR,dt_atualiza,103) = convert(CHAR,getdate(),103) 
--AND N_IDENTIFICADOR  COLLATE SQL_Latin1_General_CP1_CI_AI <> NUMCARTEIRA  COLLATE SQL_Latin1_General_CP1_CI_AI
--AND NUMCARTEIRA IS NOT NULL

--/*UBERABA*/
--UPDATE [192.168.3.12].[SecullumAcessoNet].[DBO].PESSOAS SET N_IDENTIFICADOR = NUMCARTEIRA
--FROM ZALTERACAO_CATRACA (NOLOCK)
--INNER JOIN [192.168.3.12].[SecullumAcessoNet].[DBO].PESSOAS P (NOLOCK)
--ON P.NOME COLLATE SQL_Latin1_General_CP1_CI_AI = ZALTERACAO_CATRACA.NOME COLLATE SQL_Latin1_General_CP1_CI_AI
--WHERE convert(CHAR,dt_atualiza,103) = convert(CHAR,getdate(),103)  
--AND N_IDENTIFICADOR  COLLATE SQL_Latin1_General_CP1_CI_AI <> NUMCARTEIRA  COLLATE SQL_Latin1_General_CP1_CI_AI
--AND NUMCARTEIRA IS NOT NULL

--/*ISABEL*/
--UPDATE [192.168.2.12].[SecullumAcessoNet].[DBO].PESSOAS SET N_IDENTIFICADOR = NUMCARTEIRA
--FROM ZALTERACAO_CATRACA (NOLOCK)
--INNER JOIN [192.168.2.12].[SecullumAcessoNet].[DBO].PESSOAS P (NOLOCK)
--ON P.NOME COLLATE SQL_Latin1_General_CP1_CI_AI = ZALTERACAO_CATRACA.NOME COLLATE SQL_Latin1_General_CP1_CI_AI
--WHERE convert(CHAR,dt_atualiza,103) = convert(CHAR,getdate(),103) 
--AND N_IDENTIFICADOR  COLLATE SQL_Latin1_General_CP1_CI_AI <> NUMCARTEIRA  COLLATE SQL_Latin1_General_CP1_CI_AI
--AND NUMCARTEIRA IS NOT NULL






