SELECT DISTINCT B.NOME, E.NOME 'CURSO', H.CODPERLET, H.DESCRICAO, J.NOME 'DISCIPLINA', CONVERT(VARCHAR, GETDATE(), 103) 'DATAATUAL',
				A.RA, K.DESCRICAO 'TIPO-MAT', F.CODTURMA,
				M.DESCRICAO+' '+B.RUA+', '+B.NUMERO 'RUA', N.DESCRICAO+' '+B.BAIRRO 'BAIRRO', B.CIDADE+'-'+B.ESTADO 'ESTADO', B.CEP, B.TELEFONE1 'TELEFONE', B.TELEFONE2 'CELULAR'
FROM SALUNO A
INNER JOIN PPESSOA B ON B.CODIGO = A.CODPESSOA
INNER JOIN SMATRICPL C ON C.CODCOLIGADA = A.CODCOLIGADA AND C.RA = A.RA
INNER JOIN SHABILITACAOFILIAL D ON A.CODCOLIGADA = C.CODCOLIGADA AND A.RA = C.RA AND C.IDHABILITACAOFILIAL = D.IDHABILITACAOFILIAL
INNER JOIN SCURSO E ON E.CODCURSO = D.CODCURSO
INNER JOIN STURMA F ON F.CODCOLIGADA = C.CODCOLIGADA AND F.CODFILIAL = C.CODFILIAL AND F.CODTURMA = C.CODTURMA AND F.IDPERLET = C.IDPERLET
INNER JOIN SMATRICULA G ON G.CODCOLIGADA = C.CODCOLIGADA AND C.IDPERLET=G.IDPERLET AND C.IDHABILITACAOFILIAL=G.IDHABILITACAOFILIAL AND G.RA = C.RA
INNER JOIN SPLETIVO H ON H.CODCOLIGADA = C.CODCOLIGADA AND H.IDPERLET = C.IDPERLET
INNER JOIN STURMADISC I ON G.IDTURMADISC = I.IDTURMADISC
INNER JOIN SDISCIPLINA J ON J.CODDISC = I.CODDISC
INNER JOIN STIPOMATRICULA K ON K.CODTIPOMAT = C.CODTIPOMAT
LEFT JOIN DTIPORUA M ON M.CODIGO = B.CODTIPORUA
LEFT JOIN DTIPOBAIRRO N ON N.CODIGO = B.CODTIPOBAIRRO
WHERE
A.RA='0000138'
AND H.CODPERLET='2019-1'
ORDER BY 1

--SELECT * FROM GLINKSREL WHERE MASTERTABLE='SMATRICULA' AND CHILDTABLE='STURMADISC'