
SELECT DISTINCT PPESSOA.NOME, STURMA.CODTURMA, 
CASE
	WHEN SHORARIO.CODTURNO=1 THEN 'MANHA'
	WHEN SHORARIO.CODTURNO=2 THEN 'TARDE'
	WHEN SHORARIO.CODTURNO=3 THEN 'NOITE'
END 'TURNO',
CASE 
	WHEN SHORARIO.DIASEMANA=1 THEN 'DOMINGO'
	WHEN SHORARIO.DIASEMANA=2 THEN 'SEGUNDA'
	WHEN SHORARIO.DIASEMANA=3 THEN 'TERÇA'
	WHEN SHORARIO.DIASEMANA=4 THEN 'QUARTA'
	WHEN SHORARIO.DIASEMANA=5 THEN 'QUINTA'
	WHEN SHORARIO.DIASEMANA=6 THEN 'SEXTA'
	WHEN SHORARIO.DIASEMANA=7 THEN 'SABADO'
END 'DIASEMANA',

SHORARIO.HORAINICIAL, SHORARIO.HORAFINAL 
FROM STURMA
INNER JOIN STURMADISC ON STURMADISC.CODCOLIGADA = STURMA.CODCOLIGADA AND STURMADISC.CODFILIAL = STURMA.CODFILIAL AND STURMADISC.CODTURMA = STURMA.CODTURMA AND STURMADISC.IDPERLET = STURMA.IDPERLET
INNER JOIN SPLETIVO ON SPLETIVO.CODCOLIGADA = STURMA.CODCOLIGADA AND SPLETIVO.IDPERLET = STURMA.IDPERLET
INNER JOIN SPROFESSORTURMA ON SPROFESSORTURMA.CODCOLIGADA = STURMADISC.CODCOLIGADA AND SPROFESSORTURMA.IDTURMADISC = STURMADISC.IDTURMADISC
INNER JOIN SHORARIOPROFESSOR ON SHORARIOPROFESSOR.CODCOLIGADA = SPROFESSORTURMA.CODCOLIGADA AND SHORARIOPROFESSOR.IDPROFESSORTURMA = SPROFESSORTURMA.IDPROFESSORTURMA
INNER JOIN SPROFESSOR ON SPROFESSOR.CODCOLIGADA = SPROFESSORTURMA.CODCOLIGADA AND SPROFESSOR.CODPROF = SPROFESSORTURMA.CODPROF
INNER JOIN SHORARIOTURMA ON SHORARIOTURMA.CODCOLIGADA = STURMADISC.CODCOLIGADA AND SHORARIOTURMA.IDTURMADISC = STURMADISC.IDTURMADISC
INNER JOIN SHORARIO ON SHORARIO.CODCOLIGADA=SHORARIOTURMA.CODCOLIGADA AND SHORARIO.CODHOR = SHORARIOTURMA.CODHOR
INNER JOIN PPESSOA ON SPROFESSOR.CODPESSOA = PPESSOA.CODIGO
WHERE
SPLETIVO.CODPERLET='2-2018'
