with 
Consulta as (
SELECT 
CASE 
		EVA.tipo_acesso
	WHEN 1 THEN DBO.CONVERTESEGUNDOSEMHORAS(EVA.HORA)
	END as 'entrada',
	CASE 
		EVA.tipo_acesso
	when 2 THEN DBO.CONVERTESEGUNDOSEMHORAS(EVA.HORA)
	END as 'saida',
	PPC.ID AS ID_PESSOAS,
	EVA.pessoa_id AS ID_EVENTOSACESSOS,
	CONVERT (DATETIME, EVA.DATA, 126)AS DATA_CONVERTIDA,
	DBO.CONVERTESEGUNDOSEMHORAS(EVA.HORA) AS HORAS_CONVERTIDA,
	EVA.DATA AS DATA_DE_ACESSO,
	EVA.hora,
	EVA.equipamento_id,
	EVA.tipo_acesso,
	EVA.descricao,
	EVA.negado,
	PPC.n_identificador AS MATRICULA,
	PPC.NOME AS NOME_PESSOA,
	SMA.NUMCARTEIRA AS NUMEROCARTEIR,
	SMA.CODTURMA,
	EVA.DATA AS DATA_EVA
FROM 
	[192.168.6.12].[SecullumAcessoNet].[DBO].PESSOAS  PPC (NOLOCK ) 
	LEFT JOIN [192.168.6.12].[SecullumAcessoNet].[DBO].eventos_acessos EVA (NOLOCK) ON  PPC.id = EVA.pessoa_id 
	LEFT JOIN SMATRICPL SMA (NOLOCK) ON  SMA.NUMCARTEIRA COLLATE SQL_Latin1_General_CP1_CI_AI = PPC.n_identificador COLLATE SQL_Latin1_General_CP1_CI_AI
where
--sma.ra='14944472' and
SMA.NUMCARTEIRA = '14944472' AND
 CONVERT (DATETIME, EVA.DATA) = '2018-07-05'
),
Ponto_Seq as (
SELECT MATRICULA, DATA_DE_ACESSO, HORAS_CONVERTIDA, tipo_acesso,
       Seq= row_number() over (partition by MATRICULA, DATA_DE_ACESSO order by HORA)
  from Consulta
),  
Ponto_entrada as (
SELECT MATRICULA, DATA_DE_ACESSO, HORAS_CONVERTIDA, Seq
  from Ponto_Seq
  where tipo_acesso = 1
),
Ponto_saída as (
SELECT MATRICULA, DATA_DE_ACESSO, HORAS_CONVERTIDA, Seq
  from Ponto_Seq
  where tipo_acesso = 2
)


--SELECT
--SET4.OBSERVACOES,
--SET4.OBSERVACOES1,
--SET4.DATA_DE_ACESSO,
--'1' DISPONIVELWEB,
--'mestre' RECCREATEDBY,
--GETDATE() RECCREATEDON,
--'mestre' RECMODIFIEDBY,
--GETDATE() RECMODIFIEDON,
--'N' RESPONSAVELCIENTE
--FROM

--(
SELECT *
FROM
(SELECT 

	CASE 
		WHEN SET1.ENTRADA_ACESSO IS NOT NULL THEN '2 - ALUNO ENTROU NO COLEGIO ÀS '+SET1.ENTRADA_ACESSO
	END  'OBSERVACOES',
	CASE 
		WHEN SET1.SAIDA_ACESSO IS NOT NULL THEN '5 - O ALUNO SAIU DO COLÉGIO ÀS '+SET1.SAIDA_ACESSO  
	END  'OBSERVACOES1',
SET1.MATRICULA, SET1.DATA_DE_ACESSO--, SET1.ENTRADA_ACESSO, SET1.SAIDA_ACESSO
FROM
(
SELECT 
	   coalesce(P1.MATRICULA, P2.MATRICULA) as MATRICULA,
       coalesce(P1.DATA_DE_ACESSO, P2.DATA_DE_ACESSO) as DATA_DE_ACESSO,
       P1.HORAS_CONVERTIDA as ENTRADA_ACESSO,
       P2.HORAS_CONVERTIDA as SAIDA_ACESSO
  from Ponto_entrada as P1
       full outer join Ponto_saída as P2 on P1.MATRICULA = P2.MATRICULA
                                          and P1.DATA_DE_ACESSO = P2.DATA_DE_ACESSO
                                          and P1.Seq = P2.Seq -1
)SET1
)SET4
--PIVOT										  
--(
--  MAX(DATA_DE_ACESSO) for OBSERVACAO in ([OBSERVACAO])
--) AS P