SELECT * 
FROM SOCORRENCIAALUNO
WHERE YEAR(DATAOCORRENCIA) = '2018' AND MONTH(DATAOCORRENCIA) = '05' AND DAY(DATAOCORRENCIA) = '16'  AND CODOCORRENCIAGRUPO=11 --AND CODOCORRENCIATIPO=144
AND RA IN (SELECT RA FROM SMATRICPL WHERE CODFILIAL=4 AND CODCOLIGADA=1) AND RA='04201600006'


--SELECT * FROM SMATRICPL WHERE RA='418002283'


select 
CASE WHEN EVA.tipo_acesso = '1' THEN DBO.CONVERTESEGUNDOSEMHORAS(EVA.HORA)  END AS ENTRADA_ACESSO,
CASE WHEN EVA.tipo_acesso = '2' THEN DBO.CONVERTESEGUNDOSEMHORAS(EVA.HORA)  END AS SAIDA_ACESSO,
CONVERT (DATETIME, EVA.DATA, 126)AS DATA_CONVERTIDA, * 
FROM [192.168.3.12].[SecullumAcessoNet].[DBO].PESSOAS  PPC (NOLOCK ) 
LEFT JOIN [192.168.3.12].[SecullumAcessoNet].[DBO].eventos_acessos EVA (NOLOCK) ON  PPC.id = EVA.pessoa_id 
LEFT JOIN SMATRICPL SMA (NOLOCK) ON  SMA.NUMCARTEIRA COLLATE SQL_Latin1_General_CP1_CI_AI = PPC.n_identificador COLLATE SQL_Latin1_General_CP1_CI_AI
where 
CONVERT (DATETIME, EVA.DATA) = '2018-06-15' order by 6
 and sma.ra='15020797'

select NUMCARTEIRA,* from smatricpl where ra='15020797'  2341959


SELECT * FROM SFREQUENCIA WHERE YEAR(DATA)=2018 AND MONTH(DATA)=05 RA='118003324'