SELECT 
SET3.COLIGADA,
SET3. ID_HORARIO,
SET3.ID_TURMADISCPLICA,
SET3.RA_ALUNO,
SET3.DATA_AULODISCIPLICA,
SET3.DATA_ACESSOCATRACA,
--SET1.HORAS_CONVERTIDA AS HORA_ACESSOCATRACA,
SET3.NUMEROCARTEIR,
--SET1.DESCRICAO AS TIPO_ACESSO,
--SET1.TIPO_ACESSO AS ENTRADA_SAIDA,
SET3.NOME_DISCIPLICA,
SET3.HORARIO_INICIAL_ALULA,
SET3.HORARIO_FINAL_AULA,
SET3.ENTRADA_ACESSO,
SET3.SAINDA_ACESSO,
SET3.NUMEROCARTEIRINHA,
--'11:04:26' 'SAINDA_ACESSO',
--(case when 100.0 * datediff(minute, SET3.ENTRADA_ACESSO, SET3.SAINDA_ACESSO) / datediff(minute, SET3.HORARIO_INICIAL_ALULA, SET3.HORARIO_FINAL_AULA) >= 70
--        then 'Presente'
--        else 'Falta'
--    end)
(case when 100.0 * datediff(minute, SET4.ENTRADA, SET4.SAIDA) / datediff(minute, SET3.HORARIO_INICIAL_ALULA, SET3.HORARIO_FINAL_AULA) >= 70
        then 'Presente'
        else 'Falta'
    end)
FROM
(SELECT 

SET2.CODCOLIGADA AS COLIGADA,
SET2.IDHORARIOTURMA AS ID_HORARIO,
SET2.IDTURMADISC AS ID_TURMADISCPLICA,
SET2.RA AS RA_ALUNO,
SET2.DATA as DATA_AULODISCIPLICA,
SET1.DATA_CONVERTIDA AS DATA_ACESSOCATRACA,
--SET1.HORAS_CONVERTIDA AS HORA_ACESSOCATRACA,
SET1.NUMEROCARTEIR,
SET2.NUMEROCARTEIRINHA  AS NUMEROCARTEIRINHA ,
--SET1.DESCRICAO AS TIPO_ACESSO,
--SET1.TIPO_ACESSO AS ENTRADA_SAIDA,
SET2.NOME_DISCIPLICA,
SET2.HORARIO_INICIAL_ALULA,
SET2.HORARIO_FINAL_AULA,
--SET1.ENTRADA_ACESSO,
--SET1.SAINDA_ACESSO,
MAX( 
 CASE 
     WHEN SET1.tipo_acesso = '1'   THEN HORAS_CONVERTIDA
	
	 END) AS ENTRADA_ACESSO,

MAX( 
 CASE 
     WHEN SET1.tipo_acesso = '2' THEN HORAS_CONVERTIDA
	
	 END) AS SAINDA_ACESSO
--CASE 
--	WHEN 100.0 * DATEDIFF(MINUTE, SET3.ENTRADA, SET3.SAIDA) / DATEDIFF(MINUTE, SET2.HORARIO_INICIAL_ALULA, SET2.HORARIO_FINAL_AULA ) >= 70
--        THEN 'Presente'
--        ELSE 'Falta'
--END

FROM 
(SELECT DISTINCT

E1.ID_PESSOAS,
E1.DATA_CONVERTIDA,
E1.HORAS_CONVERTIDA,
E1.MATRICULA,
E1.NUMEROCARTEIR,
E1.NOME_PESSOA,
E1.equipamento_id,
E1.TIPO_ACESSO,
E1.DESCRICAO,
E1.negado,
E1.DATA_EVA
--MAX( 
-- CASE 
--     WHEN E1.tipo_acesso = '1'   THEN HORAS_CONVERTIDA
	
--	 END) AS ENTRADA_ACESSO,

--MAX( 
-- CASE 
--     WHEN E1.tipo_acesso = '2' THEN HORAS_CONVERTIDA
	
--	 END) AS SAINDA_ACESSO


         FROM ( 
SELECT DISTINCT
PPC.ID AS ID_PESSOAS,
EVA.pessoa_id AS ID_EVENTOSACESSOS,
CONVERT (DATETIME, EVA.DATA, 126)AS DATA_CONVERTIDA,
DBO.CONVERTESEGUNDOSEMHORAS(EVA.HORA) AS HORAS_CONVERTIDA,
EVA.DATA AS DATA_DE_ACESSO,
EVA.hora,
EVA.equipamento_id,
EVA.tipo_acesso,
EVA.descricao,
EVA.negado,
PPC.n_identificador AS MATRICULA,
PPC.NOME AS NOME_PESSOA,
SMA.NUMCARTEIRA AS NUMEROCARTEIR,
SMA.CODTURMA,
EVA.DATA AS DATA_EVA


FROM [192.168.6.12].[SecullumAcessoNet].[DBO].PESSOAS  PPC (NOLOCK ) 

LEFT JOIN [192.168.6.12].[SecullumAcessoNet].[DBO].eventos_acessos EVA (NOLOCK) ON  PPC.id = EVA.pessoa_id 

LEFT JOIN SMATRICPL SMA (NOLOCK) ON  SMA.NUMCARTEIRA COLLATE SQL_Latin1_General_CP1_CI_AI = PPC.n_identificador COLLATE SQL_Latin1_General_CP1_CI_AI

) E1
--GROUP BY
--E1.ID_PESSOAS,
--E1.DATA_CONVERTIDA,
--E1.HORAS_CONVERTIDA,
--E1.MATRICULA,
--E1.NUMEROCARTEIR,
--E1.NOME_PESSOA,
--E1.equipamento_id,
--E1.TIPO_ACESSO,
--E1.DESCRICAO,
--E1.negado,
--E1.DATA_EVA

) AS SET1 INNER JOIN 



(SELECT  
SMA.NUMCARTEIRA AS NUMEROCARTEIRINHA,
SRT.IDTURMADISC AS CODIGO_DISPLICA,
SDI.NOME AS NOME_DISCIPLICA,
SHH.HORAINICIAL AS HORARIO_INICIAL_ALULA,
SHH.HORAFINAL AS HORARIO_FINAL_AULA,
SPP.DATA,
SMA.CODCOLIGADA,
SHO.IDHORARIOTURMA,
SHO.IDTURMADISC,
SMA.RA


 FROM SMATRICPL SMA (NOLOCK) 
 
 INNER JOIN STURMA STU (NOLOCK ) ON SMA.CODCOLIGADA = STU.CODCOLIGADA
                         AND        SMA.CODFILIAL   = STU.CODFILIAL
						 AND        SMA.CODTURMA    = STU.CODTURMA
				         AND        SMA.IDPERLET    = STU.IDPERLET

INNER JOIN STURMADISC SRT (NOLOCK) ON STU.CODCOLIGADA = SRT.CODCOLIGADA
						AND           STU.CODFILIAL   = SRT.CODFILIAL
						AND			  STU.CODTURMA    = SRT.CODTURMA
						AND           STU.IDPERLET    = SRT.IDPERLET

INNER JOIN SDISCIPLINA SDI (NOLOCK) ON SRT.CODCOLIGADA  = SDI.CODCOLIGADA
                      AND              SRT.CODDISC  = SDI.CODDISC

INNER JOIN SHABILITACAOFILIAL SHA (NOLOCK) ON SMA.CODCOLIGADA = SHA.CODCOLIGADA
                       AND                    SMA.IDHABILITACAOFILIAL = SHA.IDHABILITACAOFILIAL

INNER JOIN SHORARIOTURMA SHO (NOLOCK ) ON SRT.CODCOLIGADA = SHO.CODCOLIGADA 
                             AND          SRT.IDTURMADISC = SHO.IDTURMADISC

INNER JOIN SHORARIO SHH ( NOLOCK ) ON SHO.CODCOLIGADA = SHH.CODCOLIGADA
                              AND     SHO.CODHOR      = SHH.CODHOR

INNER JOIN SPLETIVO SPL (NOLOCK) ON SMA.CODCOLIGADA = SPL.CODCOLIGADA 
                              AND   SMA.CODFILIAL   = SPL.CODFILIAL
							  AND   SMA.IDPERLET    = SPL.IDPERLET

LEFT JOIN SPLANOAULA SPP (NOLOCK) ON SHO.CODCOLIGADA = SPP.CODCOLIGADA
                              AND     SHO.IDHORARIOTURMA = SPP.IDHORARIOTURMA
							  AND     SHO.CODHOR         = SPP.CODHOR


							  WHERE SPL.CODPERLET = '2018' 
							  --AND SMA.CODTURMA = 'EM01A101'
							  -- AND SMA.RA = '218001891' 
							  AND SPP.DATA = '2018-04-05' 
							  --AND SPP.IDTURMADISC = '7195'
							  AND SDI.CODCOLIGADA = '1'
							  AND SHA.CODFILIAL = '1'

							  
) SET2 ON SET1.NUMEROCARTEIR = SET2.NUMEROCARTEIRINHA

/*INICIO FUNÇÃO PRESENÇA E FALTA*/

--OUTER APPLY
--(
--    SELECT TOP(1)
--        CASE WHEN SET1.HORAS_CONVERTIDA > SET2.HORARIO_INICIAL_ALULA THEN SET1.HORAS_CONVERTIDA ELSE SET2.HORARIO_INICIAL_ALULA END Entrada,
--        CASE WHEN SET1.SAIDACATRACA < SET2.HORARIO_FINAL_AULA THEN SET1.SAIDACATRACA  ELSE SET2.HORARIO_FINAL_AULA END Saida
--    FROM SET1
--    WHERE
--        SET1.ENTRADACATRACA <= SET2.HORARIO_FINAL_AULA and
--        SET1.SAIDACATRACA >= SET2.HORARIO_INICIAL_ALULA
--) SET3

/*FIM FUNÇÃO PRESENÇA E FALTA*/

WHERE 
SET1.DATA_CONVERTIDA = SET2.DATA	AND SET1.NOME_PESSOA = 'AMANDA DE AZEVEDO CORRÊA LIMA' 
--and ENTRADA_ACESSO <= HORARIO_FINAL_AULA 
--and SAINDA_ACESSO >= HORARIO_INICIAL_ALULA

GROUP BY 

SET2.CODCOLIGADA,
SET2.RA,
SET1.NUMEROCARTEIR,
SET2.IDHORARIOTURMA,
SET2.IDTURMADISC,
SET2.DATA,
SET1.DATA_CONVERTIDA,
--SET1.HORAS_CONVERTIDA,
--SET1.DESCRICAO,
--SET1.TIPO_ACESSO,
SET2.NOME_DISCIPLICA,
--SET1.tipo_acesso,
SET2.HORARIO_INICIAL_ALULA,
SET2.HORARIO_FINAL_AULA,
SET2.NUMEROCARTEIRINHA
) SET3
outer apply
(
    select top(1)
        case when (DBO.CONVERTESEGUNDOSEMHORAS(H.HORA) > SET3.HORARIO_INICIAL_ALULA AND H.TIPO_ACESSO=1) then DBO.CONVERTESEGUNDOSEMHORAS(H.HORA)  else SET3.HORARIO_INICIAL_ALULA end as Entrada,
        case when (DBO.CONVERTESEGUNDOSEMHORAS(H.HORA) < SET3.HORARIO_FINAL_AULA AND H.TIPO_ACESSO=2) then DBO.CONVERTESEGUNDOSEMHORAS(H.HORA)  else SET3.HORARIO_FINAL_AULA end as Saida
    from [192.168.6.12].[SecullumAcessoNet].[DBO].eventos_acessos as h
    where
        (H.TIPO_ACESSO=1 AND DBO.CONVERTESEGUNDOSEMHORAS(H.HORA) <= SET3.HORARIO_FINAL_AULA)  AND
        (H.TIPO_ACESSO=2 AND DBO.CONVERTESEGUNDOSEMHORAS(H.HORA) >= SET3.HORARIO_INICIAL_ALULA) AND
		H.NUMEROCARTEIR = ST3.NUMEROCARTEIRINHA

) as SET4

  --select top(1)
  --      case when h.Entrada > a.Inicio then h.Entrada else a.Inicio end as Entrada,
  --      case when h.Saida < a.Fim then h.Saida else a.Fim end as Saida
  --  from @HorariosCatraca as h
  --  where
  --      h.Entrada <= a.Fim and
  --      h.Saida >= a.Inicio

  --SELECT * FROM [192.168.6.12].[SecullumAcessoNet].[DBO].eventos_acessos